/* BTC Hedge Assistant v8.7.2 - 60 Asset Good Position TOP10 Radar */
(()=>{
'use strict';
const VERSION='8.7.2',PAGE='top10Radar',CACHE='btc_auto_top10_v872',TTL=30*60*1000;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const clamp=v=>Math.max(0,Math.min(100,Math.round(Number(v)||0)));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const CANDIDATES=[
 ['BTCUSDT','crypto','Bitcoin'],['ETHUSDT','crypto','Ethereum'],['SOLUSDT','crypto','Solana'],['XRPUSDT','crypto','XRP'],['BNBUSDT','crypto','BNB'],['DOGEUSDT','crypto','Dogecoin'],['ADAUSDT','crypto','Cardano'],['LINKUSDT','crypto','Chainlink'],['AVAXUSDT','crypto','Avalanche'],['SUIUSDT','crypto','Sui'],['LTCUSDT','crypto','Litecoin'],['BCHUSDT','crypto','Bitcoin Cash'],['DOTUSDT','crypto','Polkadot'],['TRXUSDT','crypto','TRON'],['TONUSDT','crypto','Toncoin'],['NEARUSDT','crypto','NEAR'],['APTUSDT','crypto','Aptos'],['ARBUSDT','crypto','Arbitrum'],['OPUSDT','crypto','Optimism'],['UNIUSDT','crypto','Uniswap'],['ETCUSDT','crypto','Ethereum Classic'],['FILUSDT','crypto','Filecoin'],['ICPUSDT','crypto','Internet Computer'],['SHIBUSDT','crypto','Shiba Inu'],
 ['NVDA','us','NVIDIA'],['AAPL','us','Apple'],['MSFT','us','Microsoft'],['AMZN','us','Amazon'],['META','us','Meta'],['TSLA','us','Tesla'],['GOOGL','us','Alphabet'],['AVGO','us','Broadcom'],['AMD','us','AMD'],['NFLX','us','Netflix'],['PLTR','us','Palantir'],['ORCL','us','Oracle'],['CRM','us','Salesforce'],['INTC','us','Intel'],['COIN','us','Coinbase'],['MSTR','us','Strategy'],['SPY','us','S&P 500 ETF'],['QQQ','us','Nasdaq 100 ETF'],
 ['005930.KS','kr','삼성전자'],['000660.KS','kr','SK하이닉스'],['068270.KS','kr','셀트리온'],['005380.KS','kr','현대차'],['035420.KS','kr','NAVER'],['051910.KS','kr','LG화학'],['207940.KS','kr','삼성바이오로직스'],['006400.KS','kr','삼성SDI'],['000270.KS','kr','기아'],['105560.KS','kr','KB금융'],['055550.KS','kr','신한지주'],['035720.KS','kr','카카오'],['012450.KS','kr','한화에어로스페이스'],['028260.KS','kr','삼성물산'],['373220.KS','kr','LG에너지솔루션'],['086790.KS','kr','하나금융지주'],['066570.KS','kr','LG전자'],['009150.KS','kr','삼성전기']
].map(([symbol,type,name])=>({symbol,type,name}));
const LABEL={all:'전체',crypto:'코인',us:'미국',kr:'한국'};
let running=false,latestAuto=[],market='all';
function readCache(){try{return JSON.parse(localStorage.getItem(CACHE)||'null')}catch(e){return null}}
function writeCache(rows){try{localStorage.setItem(CACHE,JSON.stringify({ts:Date.now(),version:VERSION,rows}))}catch(e){}}
function cacheFresh(x){return x&&Array.isArray(x.rows)&&Date.now()-Number(x.ts||0)<TTL}
function direction(c){if(c.long>=57)return 'LONG';if(c.long<=43)return 'SHORT';return 'WAIT'}
function location(c,r){const d=direction(c),state=String(r?.v79?.state||r?.state||'');if(d==='LONG'){if(/과열|추격/.test(state)||c.wait>55)return '상승 우위 · 눌림 대기';if(c.long>=75&&c.consensus>=60)return 'LONG 좋은 자리 후보';return '상승 우위';}if(d==='SHORT'){if(/과매도|반등/.test(state)||c.wait>55)return '하락 우위 · 반등 대기';if(c.short>=75&&c.consensus>=60)return 'SHORT 좋은 자리 후보';return '하락 우위';}return '관망 · 방향 확인'}
function opportunity(c,r){const directional=Math.max(c.long,c.short),fresh=n(r?.freshnessScore)??80;let s=directional*.50+c.confidence*.20+c.consensus*.15+(100-c.wait)*.10+fresh*.05;if(direction(c)==='WAIT')s-=12;if(r?.isStale)s-=25;if(String(r?.dataQuality)==='낮음')s-=10;return clamp(s)}
function fallbackComposite(r){const trend=n(r?.trendScore)??50,entry=n(r?.entryScore)??50,raw=clamp(trend*.55+entry*.45),sig=String(r?.signal||r?.dir||'').toUpperCase(),isShort=/SELL|SHORT|DOWN|하락|매도/.test(sig);const long=isShort?100-raw:raw;return {long,short:100-long,wait:clamp(100-Math.abs(long-50)*1.5),confidence:clamp((trend+entry)/2),consensus:clamp(Math.abs(long-50)*2)}}
async function analyzeOne(c){if(typeof window.analyzeScannerSymbol!=='function')throw new Error('scanner not ready');const r=await window.analyzeScannerSymbol(c.symbol,c.type);let comp;try{if(window.BTCStrategyPosition?.analyzeMethods&&window.BTCStrategyPosition?.composite){const a=window.BTCStrategyPosition.analyzeMethods(r);comp=window.BTCStrategyPosition.composite(r,a.methods)}else comp=fallbackComposite(r)}catch(e){comp=fallbackComposite(r)}const row={symbol:c.symbol,type:c.type,name:r?.meta?.name||c.name,price:n(r?.price),source:r?.source||'',dataQuality:r?.dataQuality||'--',state:r?.v79?.state||r?.state||'',long:clamp(comp.long),short:clamp(comp.short),wait:clamp(comp.wait),confidence:clamp(comp.confidence),consensus:clamp(comp.consensus),freshness:clamp(n(r?.freshnessScore)??80)};row.direction=direction(row);row.location=location(row,r);row.score=opportunity(row,r);return row}
function myRows(){let arr=[];try{arr=window.BTCLearning?.records?.()||JSON.parse(localStorage.getItem('v832learning')||'[]')}catch(e){}const latest=new Map();for(const r of arr){if(r?.kind!=='scanner_signal'||!r.symbol)continue;latest.set(`${r.type}:${r.symbol}`,r)}return [...latest.values()].map(r=>{const trend=n(r.trendScore)??50,entry=n(r.entryScore)??50,raw=clamp(trend*.55+entry*.45),sig=String(r.signal||'WAIT'),short=sig==='DOWN',longScore=short?100-raw:raw,wait=clamp(100-Math.abs(longScore-50)*1.4),conf=clamp((trend+entry)/2),score=clamp(Math.max(longScore,100-longScore)*.65+conf*.25+(100-wait)*.10);return {symbol:r.symbol,type:r.type||'crypto',name:r.symbol,price:n(r.price),direction:sig==='UP'?'LONG':sig==='DOWN'?'SHORT':'WAIT',score,long:longScore,short:100-longScore,wait,confidence:conf,consensus:clamp(Math.abs(longScore-50)*2),location:r.state||'최근 분석',ts:r.ts}}).sort((a,b)=>b.score-a.score).slice(0,10)}
function rowHtml(r,i){const cls=r.direction==='LONG'?'t10Long':r.direction==='SHORT'?'t10Short':'t10Wait';return `<button class="t10Row" data-sym="${esc(r.symbol)}" data-type="${esc(r.type)}"><span class="t10Rank">#${i+1}</span><span class="t10Main"><b>${esc(r.name||r.symbol)}</b><small>${esc(r.symbol)} · ${esc(r.location||'--')}</small></span><span class="t10Dir ${cls}">${esc(r.direction)}</span><span class="t10Score">${r.score}<small>적합도</small></span><span class="t10Meta">L ${r.long} · S ${r.short}<small>신뢰 ${r.confidence}% · 합의 ${r.consensus}%</small></span></button>`}
function bindRows(root){root?.querySelectorAll('.t10Row').forEach(b=>b.addEventListener('click',()=>window.BTCStrategyPosition?.open?.(b.dataset.sym,b.dataset.type)))}
function filtered(rows){return [...rows].filter(r=>market==='all'||r.type===market).sort((a,b)=>b.score-a.score).slice(0,10)}
function counts(rows){const c={all:rows.length,crypto:0,us:0,kr:0};for(const r of rows)if(c[r.type]!=null)c[r.type]++;return c}
function setMarket(m){market=m;document.querySelectorAll('.t10Tab').forEach(b=>b.classList.toggle('active',b.dataset.market===m));renderAuto(latestAuto,$('t10Status')?.textContent||'')}
function ensureStyle(){if($('t10Style'))return;const s=document.createElement('style');s.id='t10Style';s.textContent=`#top10Radar{max-width:980px;margin:0 auto;padding:2px 0 115px}.t10Hero{background:linear-gradient(180deg,#18283d,#0d1723);border:1px solid #3a5a7f;border-radius:18px;padding:15px;margin-bottom:10px}.t10Title{font-size:23px;font-weight:900}.t10Sub{font-size:11px;color:#98a7b8;line-height:1.55;margin-top:5px}.t10Grid{display:grid;grid-template-columns:1fr 1.35fr;gap:10px}.t10Card{background:linear-gradient(180deg,#121b27,#0e1620);border:1px solid #293848;border-radius:15px;padding:11px}.t10Head{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:7px}.t10Head b{font-size:15px}.t10Tiny{font-size:10px;color:#91a0b0;line-height:1.5}.t10Rows{display:grid;gap:6px}.t10Row{display:grid;grid-template-columns:34px minmax(0,1.4fr) 58px 58px minmax(110px,.8fr);gap:7px;align-items:center;width:100%;text-align:left;border:1px solid #293a4b;background:#0b151f;border-radius:11px;padding:8px}.t10Rank{font-weight:900;color:#8fa5bc}.t10Main b{display:block;font-size:12px}.t10Main small,.t10Meta small,.t10Score small{display:block;font-size:9px;color:#8fa0b3;margin-top:2px}.t10Dir{font-size:10px;font-weight:900;text-align:center}.t10Long{color:#20d792}.t10Short{color:#ff667a}.t10Wait{color:#ffbf47}.t10Score{font-size:19px;font-weight:900;text-align:right}.t10Meta{font-size:10px;text-align:right;color:#c3cfdb}.t10Progress{height:7px;background:#1c2937;border-radius:99px;overflow:hidden;margin-top:8px}.t10Progress i{display:block;height:100%;background:#2f7cf6}.t10Btn{background:#142b46;border-color:#466b95}.t10MenuBtn{border-color:#4b6f9b!important;background:#142b46!important}.t10StrategyBtn{width:100%;margin:0 0 10px;background:#142b46;border-color:#45678d}.t10Tabs{display:flex;gap:6px;overflow:auto;margin:9px 0 8px}.t10Tab{white-space:nowrap;padding:7px 10px}.t10Tab.active{background:#2767df;border-color:#4b7fd0}.t10Summary{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.t10Chip{font-size:9px;padding:3px 6px;border:1px solid #34495e;border-radius:999px;color:#a9b8c8}@media(max-width:760px){.t10Grid{grid-template-columns:1fr}.t10Row{grid-template-columns:30px minmax(0,1fr) 52px 52px}.t10Meta{grid-column:2/-1;text-align:left}.t10Score{font-size:17px}}`;document.head.appendChild(s)}
function ensurePage(){ensureStyle();const main=document.querySelector('main');if(!main)return null;let p=$(PAGE);if(!p){p=document.createElement('section');p.id=PAGE;p.className='v853Page';p.style.display='none';main.appendChild(p)}return p}
function renderShell(){const p=ensurePage();if(!p)return;p.innerHTML=`<div class="t10Hero"><div class="t10Title">🏆 좋은 매매위치 TOP10</div><div class="t10Sub">내가 직접 분석한 종목과 앱이 자동 탐색한 시장 기회를 분리합니다. AUTO는 총 60개 고유동성 후보를 10개 전략 합의·신뢰도·관망 위험·데이터 신선도로 평가합니다.</div></div><div class="t10Grid"><div class="t10Card"><div class="t10Head"><b>내 분석 TOP10</b><span class="t10Tiny">직접 분석 기록 기준</span></div><div id="t10Mine" class="t10Rows"></div></div><div class="t10Card"><div class="t10Head"><b>AUTO 시장 TOP10</b><button id="t10Run" class="t10Btn">60종목 재분석</button></div><div id="t10Status" class="t10Tiny">대기</div><div class="t10Progress"><i id="t10Bar" style="width:0%"></i></div><div class="t10Tabs"><button class="t10Tab active" data-market="all">전체</button><button class="t10Tab" data-market="crypto">코인</button><button class="t10Tab" data-market="us">미국</button><button class="t10Tab" data-market="kr">한국</button></div><div id="t10Summary" class="t10Summary"></div><div id="t10Auto" class="t10Rows" style="margin-top:8px"></div></div></div>`;renderMine();document.querySelectorAll('.t10Tab').forEach(b=>b.addEventListener('click',()=>setMarket(b.dataset.market)));const c=readCache();if(c?.rows?.length){latestAuto=c.rows;renderAuto(c.rows,`최근 자동분석 · ${Math.round((Date.now()-c.ts)/60000)}분 전`)}else renderAuto([],'자동분석 대기');$('t10Run')?.addEventListener('click',()=>runAuto(true))}
function renderMine(){const box=$('t10Mine');if(!box)return;const rows=myRows();box.innerHTML=rows.length?rows.map(rowHtml).join(''):'<div class="t10Tiny">아직 직접 분석 기록이 없습니다. 스캐너에서 종목을 분석하면 여기에 누적됩니다.</div>';bindRows(box)}
function renderAuto(rows,status){const box=$('t10Auto');if(!box)return;latestAuto=rows||[];const show=filtered(latestAuto);box.innerHTML=show.length?show.map(rowHtml).join(''):`<div class="t10Tiny">${LABEL[market]} 시장에 표시할 자동분석 결과가 아직 없습니다.</div>`;if($('t10Status'))$('t10Status').textContent=status||'';const c=counts(latestAuto);if($('t10Summary'))$('t10Summary').innerHTML=`<span class="t10Chip">전체 ${c.all}</span><span class="t10Chip">코인 ${c.crypto}</span><span class="t10Chip">미국 ${c.us}</span><span class="t10Chip">한국 ${c.kr}</span><span class="t10Chip">현재 ${LABEL[market]} TOP10</span>`;bindRows(box)}
async function waitReady(ms=9000){const end=Date.now()+ms;while(Date.now()<end){if(typeof window.analyzeScannerSymbol==='function'&&window.BTCStrategyPosition?.analyzeMethods)return true;await sleep(250)}return typeof window.analyzeScannerSymbol==='function'}
function snapshotLocal(){const snap={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k==='v832learning'||k.startsWith('v80perf:')||k.startsWith('v79hist:'))snap[k]=localStorage.getItem(k)}return snap}
function restoreLocal(snap){const remove=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k==='v832learning'||k.startsWith('v80perf:')||k.startsWith('v79hist:'))if(!(k in snap))remove.push(k)}remove.forEach(k=>localStorage.removeItem(k));Object.entries(snap).forEach(([k,v])=>localStorage.setItem(k,v))}
async function runAuto(force=false){if(running)return;const cached=readCache();if(!force&&cacheFresh(cached)){latestAuto=cached.rows;renderAuto(cached.rows,`캐시 사용 · ${Math.round((Date.now()-cached.ts)/60000)}분 전`);return}running=true;const btn=$('t10Run');if(btn){btn.disabled=true;btn.textContent='60종목 분석 중...'}const status=$('t10Status'),bar=$('t10Bar');const ok=await waitReady();if(!ok){if(status)status.textContent='분석 엔진 준비 실패 · 앱을 다시 열어 주세요.';running=false;if(btn){btn.disabled=false;btn.textContent='60종목 재분석'}return}let cursor=0,done=0,rows=[],fails=0;const snap=snapshotLocal();window.__BTC_AUTO_SCAN=true;try{async function worker(){while(true){const i=cursor++;if(i>=CANDIDATES.length)return;const c=CANDIDATES[i];if(status)status.textContent=`자동 분석 ${done+1}/${CANDIDATES.length} · ${c.name}`;try{rows.push(await analyzeOne(c))}catch(e){fails++}finally{done++;if(bar)bar.style.width=`${Math.round(done/CANDIDATES.length*100)}%`;renderAuto([...rows],`진행 ${done}/${CANDIDATES.length} · 성공 ${rows.length} · 실패 ${fails}`);await sleep(120)}}}await Promise.all([worker(),worker(),worker(),worker()]);rows.sort((a,b)=>b.score-a.score);latestAuto=rows;writeCache(rows);renderAuto(rows,`완료 · 후보 ${CANDIDATES.length}개 중 ${rows.length}개 성공 · ${new Date().toLocaleTimeString()}`)}finally{window.__BTC_AUTO_SCAN=false;restoreLocal(snap);running=false;if(btn){btn.disabled=false;btn.textContent='60종목 재분석'}}}
function open(){renderShell();const p=$(PAGE);if(window.BTCV853?.activatePane)window.BTCV853.activatePane(p,'more');else{document.querySelectorAll('main>section').forEach(x=>x.style.display='none');p.style.display='block';window.scrollTo(0,0)}setTimeout(()=>runAuto(false),150)}
function hookMore(){const m=$('v850MorePane');if(!m)return;const menu=m.querySelector('.v850Menu');if(!menu||m.querySelector('.t10MenuBtn'))return;const b=document.createElement('button');b.className='t10MenuBtn';b.innerHTML='<b>🏆 좋은 매매위치 TOP10</b><span>60종목 자동탐색 · 전체/코인/미국/한국 TOP10</span>';b.addEventListener('click',open);menu.insertBefore(b,menu.firstChild)}
function hookStrategy(){const p=$('strategyPosition');if(!p||$('t10StrategyBtn'))return;const hero=p.querySelector('.spHero');if(!hero)return;const b=document.createElement('button');b.id='t10StrategyBtn';b.className='t10StrategyBtn';b.textContent='🏆 좋은 매매위치 TOP10 보기';b.addEventListener('click',open);hero.insertAdjacentElement('afterend',b)}
function init(){ensureStyle();hookMore();hookStrategy();new MutationObserver(()=>{hookMore();hookStrategy()}).observe(document.body,{childList:true,subtree:true});window.BTCAutoTop10={open,run:()=>runAuto(true),get:()=>latestAuto.slice(),candidates:()=>CANDIDATES.slice(),setMarket}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,1200));else setTimeout(init,1200);
})();
