/* BTC Hedge Assistant v8.10.0 - Bidirectional Cycle Monetization Engine */
(()=>{'use strict';
const V='8.10.0'; const $=id=>document.getElementById(id); const n=v=>Number.isFinite(Number(v))?Number(v):null;
function M(){try{return typeof market!=='undefined'?market:(window.market||{})}catch(e){return window.market||{}}}
function P(){try{return typeof pos==='function'?pos():(window.pos?.())}catch(e){return null}}
function close4(){return (M()?.h4||[]).map(r=>Number(Array.isArray(r)?r[4]:(r.close??r.c))).filter(Number.isFinite)}
function ema(a,p){let e=null,k=2/(p+1);return a.map(v=>(e=e==null?v:v*k+e*(1-k)))}
function dd(eq){let pk=eq[0]||0,m=0;for(const x of eq){pk=Math.max(pk,x);m=Math.max(m,pk-x)}return m}
function sim(px,d,cycle){let lq=d.lq,sq=d.sq,lr=0,sr=0,fees=0,lastL=-99,lastS=-99;const fee=(n(d.feeRate)||.04)/100,e20=ema(px,20),e50=ema(px,50),eq=[];const baseL=lq,baseS=sq,step=Math.max(.02,n(d.stepQty)||.2);for(let i=1;i<px.length;i++){const p=px[i],bull=p>e20[i]&&e20[i]>e50[i],bear=p<e20[i]&&e20[i]<e50[i],conf80=p>80000&&px[i-1]>80000;
// confirmed short-loss reduction: never below 25% base short
if(conf80&&bull&&i-lastS>=6&&sq>baseS*.25){let target=p>d.le?baseS*.25:baseS*.5625,q=Math.min(step,Math.max(0,sq-target));if(q>0){sr+=(d.se-p)*q;fees+=p*q*fee;sq-=q;lastS=i}}
// cycle extension: monetize long only after profit + confirmed trend; keep >=35% core long
if(cycle&&p>d.le&&bull&&i-lastL>=6&&lq>baseL*.35){const gain=(p/d.le-1)*100;let target=gain>=20?baseL*.35:gain>=12?baseL*.50:gain>=6?baseL*.70:baseL;let q=Math.min(step,Math.max(0,lq-target));if(q>0){lr+=(p-d.le)*q;fees+=p*q*fee;lq-=q;lastL=i}}
// bearish reversal freezes all loss-side trimming; profitable short is preserved for later manual profit-taking
const equity=(n(d.wallet)||0)+(n(d.added)||0)+lr+sr-fees+lq*(p-d.le)+sq*(d.se-p);eq.push(equity)}return {end:eq.at(-1)||0,mdd:dd(eq),lq,sq,longReal:lr,shortReal:sr,fees,trades:null}}
function stress(d){const paths={REVERSAL_100_70:[80,82,85,88,92,96,100,98,95,91,87,82,78,74,70],CONTINUE_100_120:[80,84,88,92,96,100,104,108,112,116,120],WHIP_100_85_105:[80,84,90,96,100,96,91,87,85,89,94,99,105]};let out={};for(const [k,a] of Object.entries(paths)){let px=[];for(let j=0;j<a.length-1;j++){for(let z=0;z<8;z++)px.push((a[j]+(a[j+1]-a[j])*z/8)*1000)}px.push(a.at(-1)*1000);while(px.length<55)px.unshift(px[0]);const b=sim(px,d,false),c=sim(px,d,true);out[k]={base:b,cycle:c,delta:c.end-b.end,mddDelta:c.mdd-b.mdd}}return out}
function historical(d){const a=close4();if(a.length<120)return null;let W=[];for(let i=60;i<a.length-60;i++)if(a[i-1]<80000&&a[i]>=80000){const px=a.slice(Math.max(0,i-50),Math.min(a.length,i+181)),b=sim(px,d,false),c=sim(px,d,true);W.push({b,c})}W=W.slice(-12);if(!W.length)return null;const av=(f)=>W.reduce((s,x)=>s+f(x),0)/W.length,w=W.filter(x=>x.c.end>=x.b.end).length/W.length*100;return {windows:W.length,win:w,baseEnd:av(x=>x.b.end),cycleEnd:av(x=>x.c.end),baseMdd:av(x=>x.b.mdd),cycleMdd:av(x=>x.c.mdd)} }
function test(){const d=P();if(!d?.lq||!d?.sq)return null;const h=historical(d),s=stress(d);const rev=s.REVERSAL_100_70,cont=s.CONTINUE_100_120,whip=s.WHIP_100_85_105;const histOK=!h||(h.win>=50&&h.cycleMdd<=h.baseMdd*1.05);const reversalOK=rev.cycle.mdd<=rev.base.mdd*.9;const continuationCost=Math.max(0,cont.base.end-cont.cycle.end);const continuationCap=Math.max(1500,Math.abs(cont.base.end)*.12);const robust=histOK&&reversalOK&&continuationCost<=continuationCap;return {h,s,robust,continuationCost}}
function ensure(){let c=$('cycleHedgeCard');if(c)return c;const a=$('dynamicHedgeCard');if(!a)return null;c=document.createElement('div');c.id='cycleHedgeCard';c.className='card';a.insertAdjacentElement('afterend',c);return c}
const f=v=>Number.isFinite(v)?Math.round(v).toLocaleString():'--';
function render(){const c=ensure();if(!c)return;const x=test();if(!x){c.innerHTML='<b>🔄 양방향 사이클 백테스트</b><div class="small">포지션/4H 데이터를 기다리는 중...</div>';return}const r=x.s.REVERSAL_100_70,q=x.s.CONTINUE_100_120,w=x.s.WHIP_100_85_105,h=x.h;c.innerHTML=`<div class="row"><div><b>🔄 양방향 사이클 수익화 엔진</b><div class="small">상승 시 롱 수익화 + 숏 손실 제한 + 반락 시 남은 숏 보존</div></div><span class="badge">v${V} · ${x.robust?'ADAPTIVE':'BASE'}</span></div><div class="${x.robust?'okbox':'warnbox'}"><b>${x.robust?'사이클 전략 채택':'기존 하이브리드 유지'}</b><br>${x.robust?'현재 포지션 기준 역사/스트레스 가드를 통과했습니다.':'계속 상승장에서의 기회비용 또는 역사구간 검증 기준을 통과하지 못했습니다.'}</div><div class="grid3"><div class="kpi"><div class="small">100K→70K MDD</div><b>${f(r.base.mdd)} → ${f(r.cycle.mdd)}</b></div><div class="kpi"><div class="small">100K→120K 최종차이</div><b>${f(q.cycle.end-q.base.end)}</b></div><div class="kpi"><div class="small">100→85→105 최종차이</div><b>${f(w.cycle.end-w.base.end)}</b></div></div><div class="notice">${h?`실제 4H 80K 돌파 ${h.windows}구간: 사이클 우위 ${h.win.toFixed(0)}% · 평균 MDD ${f(h.baseMdd)} → ${f(h.cycleMdd)}`:'실제 4H 비교구간 부족'}<br>가드: 롱은 평단 위 + 4H 상승 확인 후만 익절하며 최소 35% 코어를 남깁니다. 약세 전환 시 추가 롱 익절/숏 손실축소를 중단합니다. 자동 숏 재구축은 하지 않습니다.</div>`}
function boot(){let k=0,t=setInterval(()=>{render();if(++k>20)clearInterval(t)},900);setInterval(render,30000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.BTCCycleHedge={version:V,test,render};})();