/* BTC Hedge Assistant v8.16.0 - Execution Reality + Final Exit Engine */
(()=>{'use strict';
const V='8.16.0',K='btc_execution_exit_v8160',$=id=>document.getElementById(id),clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),N=v=>Number.isFinite(Number(v))?Number(v):null;
let FUND={rate:null,at:0,source:'대기'},LAST=null;
function M(){try{return typeof market!=='undefined'?market:(window.market||{})}catch(e){return window.market||{}}}
function P(){try{return typeof pos==='function'?pos():(window.pos?.())}catch(e){return null}}
function rows(tf){const a=M()?.[tf]||[];return Array.isArray(a)?a:[]}
function price(){return Number(M()?.price)||Number((rows('h4').at(-1)||[])[4])||0}
function atrPct(){const a=rows('h4');if(a.length<20)return .03;let tr=[];for(let i=1;i<a.length;i++){const hi=Number(Array.isArray(a[i])?a[i][2]:a[i].high),lo=Number(Array.isArray(a[i])?a[i][3]:a[i].low),pc=Number(Array.isArray(a[i-1])?a[i-1][4]:a[i-1].close);if([hi,lo,pc].every(Number.isFinite))tr.push(Math.max(hi-lo,Math.abs(hi-pc),Math.abs(lo-pc)))}const x=tr.slice(-14),p=price()||1;return x.length?x.reduce((s,v)=>s+v,0)/x.length/p:.03}
function feeRate(d){return (N(d?.feeRate)||.04)/100}
function slippageRate(){const v=atrPct(),bps=clamp(2+v*10000*.02,2,12);return bps/10000}
function reality(d){const fee=feeRate(d),slip=slippageRate(),oneWay=fee+slip,roundTrip=2*oneWay;return{fee,slip,oneWay,roundTrip,atr:atrPct()}}
async function funding(){if(Date.now()-FUND.at<300000&&FUND.rate!=null)return FUND;try{const r=await fetch('https://fapi.binance.com/fapi/v1/premiumIndex?symbol=BTCUSDT',{cache:'no-store'}),j=await r.json(),x=Number(j.lastFundingRate);if(Number.isFinite(x))FUND={rate:x,at:Date.now(),source:'Binance 현재 펀딩'};else throw new Error('rate')}catch(e){FUND={rate:null,at:Date.now(),source:'펀딩 미확인 · 계산 제외'}}return FUND}
function rawClose(d,p){return(N(d.wallet)||0)+(N(d.added)||0)+(N(d.lq)||0)*(p-N(d.le))+(N(d.sq)||0)*(N(d.se)-p)}
function closeCost(d,p,r=reality(d)){return p*((N(d.lq)||0)+(N(d.sq)||0))*r.oneWay}
function netClose(d,p,r=reality(d)){return rawClose(d,p)-closeCost(d,p,r)}
function funding24h(d,p){if(FUND.rate==null)return null;return ((N(d.sq)||0)-(N(d.lq)||0))*p*FUND.rate*3}
function optimizer(){try{return window.BTCAdaptiveLearning?.recommendation?.()||null}catch(e){return null}}
function regime(){try{const s=window.BTCRegimeHedge?.trendScore?.()?.score??50;return{score:s,name:s>=72?'BULL':s<=28?'BEAR':'TRANSITION'}}catch(e){return{score:50,name:'TRANSITION'}}}
function gate(){const action=String($('nextNow')?.textContent||'').trim(),txt=String($('conditionScore')?.textContent||'').trim(),m=txt.match(/(\d+)\s*\/\s*(\d+)/);return{action,ok:m?+m[1]:0,total:m?+m[2]:0,ready:!!m&&+m[1]>=+m[2]}}
function state(){try{return JSON.parse(localStorage.getItem(K)||'null')||{}}catch(e){return{}}}function save(x){try{localStorage.setItem(K,JSON.stringify(x))}catch(e){}}
function scenario(d,p,r,rg){const a=r.atr,sc=rg.score,up=clamp((sc-50)/50,-1,1),nodes=[-2,-1,0,1,2],weights=nodes.map(k=>Math.exp(k*up*.8));const z=weights.reduce((s,x)=>s+x,0);let vals=[];for(let i=0;i<nodes.length;i++){const pp=Math.max(1000,p*(1+nodes[i]*a)),w=weights[i]/z;vals.push({k:nodes[i],p:pp,w,net:netClose(d,pp,r)})}const exp=vals.reduce((s,x)=>s+x.net*x.w,0),worst=Math.min(...vals.map(x=>x.net)),best=Math.max(...vals.map(x=>x.net));return{vals,exp,worst,best}}
function trimCandidate(d,p,r,opt,rg){if(!opt?.healthy)return{side:'NONE',qty:0,cost:0,reason:'Optimizer 미연결'};const g=gate();if(!g.ready||rg.name==='TRANSITION')return{side:'NONE',qty:0,cost:0,reason:'실행조건 미충족 또는 전환장'};const maxStep=.05;let side='NONE',qty=0;if(rg.name==='BULL'){const desired=Math.max(0,(N(d.sq)||0)*(1-opt.shortKeep));side='SHORT';qty=Math.min(maxStep,desired)}else if(rg.name==='BEAR'){const desired=Math.max(0,(N(d.lq)||0)*(1-opt.longKeep));side='LONG';qty=Math.min(maxStep,desired)}const cost=p*qty*r.oneWay;return{side,qty,cost,reason:qty>0?'Optimizer 목표비율 + 실행조건 충족':'현재 비율상 추가 축소 불필요'}}
function exitDecision(d,p,r,opt,rg){let st=state(),now=netClose(d,p,r),target=N(d.wallet)||69936.30;st.peak=Math.max(N(st.peak)||now,now);st.target=st.target||target;const recovered=now>=st.target,lock=recovered?Math.max(st.target,st.peak*.92):null,dd=st.peak>0?(st.peak-now)/st.peak:0;let code='HOLD',title='🟡 추세 유지 · 전량종료 대기',why='목표 Wallet 미회복: 장세 추종과 10K Guard 우선';if(recovered){if(now<=lock){code='EXIT';title='🟢 전량 종료 검토';why=`Recovery Lock ${money(lock)} 도달/이탈: 회복자금 보호 우선`}else if(rg.name==='TRANSITION'||(rg.score>42&&rg.score<58)){code='LOCK';title='🔵 수익 잠금 우선';why=`목표 회복 완료 · 전환장 진입: 최고 전량청산가치의 92%를 보호`}else{code='TRAIL';title='🟢 수익 추종 계속';why=`목표 회복 완료 · ${rg.name} 추세 유지, Recovery Lock ${money(lock)} 적용`}}save({...st,last:now,at:Date.now()});return{code,title,why,now,target,peak:st.peak,lock,dd,recovered}}
const money=x=>Number.isFinite(x)?'$'+Math.round(x).toLocaleString():'--',pct=x=>Number.isFinite(x)?(x*100).toFixed(2)+'%':'--';
function pane(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function ensure(){let c=$('executionExitCard');if(!c){c=document.createElement('div');c.id='executionExitCard';c.className='card'}const p=pane();if(p&&c.parentElement!==p){const a=$('recoveryEngineCard')||$('adaptiveLearningCard');if(a&&a.parentElement===p)a.insertAdjacentElement('afterend',c);else p.appendChild(c)}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.cssText+=';display:block;width:100%;max-width:100%;min-width:0';return c}
function render(){const c=ensure(),d=P(),p=price();if(!c)return;if(!d||!p){c.innerHTML=`<div class="row"><b>🎯 Execution Reality + Final Exit</b><span class="badge">v${V}</span></div><div class="small">포지션/시장 데이터 대기 중...</div>`;return}const r=reality(d),opt=optimizer(),rg=regime(),sc=scenario(d,p,r,rg),tc=trimCandidate(d,p,r,opt,rg),ex=exitDecision(d,p,r,opt,rg),f24=funding24h(d,p),tone=ex.code==='EXIT'||ex.code==='TRAIL'?'okbox':ex.code==='LOCK'?'warnbox':'warnbox',fundTxt=f24==null?'미확인':`${f24>=0?'+':''}${money(f24)}`;c.innerHTML=`<div class="row"><div><b>🎯 Execution Reality + Final Exit</b><div class="small">실전비용 보정 · 최종 양포지션 종료 판단</div></div><span class="badge">v${V}</span></div><div class="${tone}" style="margin-top:8px"><b style="font-size:18px">${ex.title}</b><br>${ex.why}</div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">실전 전량청산가치</div><b>${money(ex.now)}</b><div class="tiny">수수료+슬리피지 반영</div></div><div class="kpi"><div class="small">Recovery Lock</div><b>${ex.lock?money(ex.lock):'대기'}</b><div class="tiny">최고값 ${money(ex.peak)}</div></div><div class="kpi"><div class="small">현재 회복률</div><b>${pct(ex.now/ex.target)}</b></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">편도 거래비용</div><b>${pct(r.oneWay)}</b><div class="tiny">수수료 ${pct(r.fee)} + 슬리피지 ${pct(r.slip)}</div></div><div class="kpi"><div class="small">24H 순펀딩 추정</div><b>${fundTxt}</b><div class="tiny">${FUND.source}</div></div><div class="kpi"><div class="small">2ATR 스트레스</div><b>${money(sc.worst)}</b><div class="tiny">기대 ${money(sc.exp)} · 상단 ${money(sc.best)}</div></div></div><div class="${tc.qty>0?'okbox':'warnbox'}"><b>${tc.qty>0?`실행 후보: ${tc.side==='SHORT'?'숏':'롱'} ${tc.qty.toFixed(3)} BTC 축소 검토`:'실행 후보 없음 · 관망'}</b><br>${tc.reason}${tc.qty>0?` · 예상 체결비용 ${money(tc.cost)}`:''}</div><details style="margin-top:9px"><summary class="small"><b>계산 기준 보기</b></summary><div class="tiny" style="line-height:1.65;margin-top:6px">4H ATR ${pct(r.atr)} · 슬리피지는 ATR에 따라 2~12bp 범위에서 보정 · 전량청산가치는 현재 포지션 손익에서 편도 수수료와 추정 슬리피지를 차감합니다. 펀딩은 Binance 현재 펀딩을 읽을 수 있을 때만 24시간 순효과를 표시하며, 실패 시 최종가치 계산에는 억지로 넣지 않습니다. 전량 종료 신호는 목표 Wallet 회복 후 최고 실전청산가치의 92% Recovery Lock과 장세 전환을 함께 봅니다.</div></details>`;LAST={r,opt,rg,sc,tc,ex,f24};}
function boot(){funding().finally(render);render();[1000,3000,8000].forEach(x=>setTimeout(()=>funding().finally(render),x));setInterval(()=>funding().finally(render),60000);document.addEventListener('btc-adaptive-ready',()=>setTimeout(render,30))}
window.BTCExecutionExit={version:V,reality,netClose,scenario,exitDecision,recommendation:()=>LAST};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();