/* BTC Hedge Assistant v8.8.1 - Opportunity Radar V2.1 */
(()=>{
'use strict';
const VERSION='8.8.1';
const AUTO_KEY='btc_auto_top10_v872',HIST_KEY='btc_top10_history_v873',ENRICH_KEY='btc_opp_enrich_v881',PERF_KEY='btc_strategy_perf_v880',ALERT_KEY='btc_opp_alert_v880';
const TTL=30*60*1000;
const $=id=>document.getElementById(id);
const n=v=>Number.isFinite(Number(v))?Number(v):null;
const clamp=v=>Math.max(0,Math.min(100,Math.round(Number(v)||0)));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const auto=()=>load(AUTO_KEY,null),hist=()=>load(HIST_KEY,[]),perf=()=>load(PERF_KEY,{}),enrichCache=()=>load(ENRICH_KEY,{});
let market='all',running=false;
const marketLabel=m=>m==='crypto'?'코인':m==='us'?'미국':m==='kr'?'한국':'전체';
function ranked(rows,m='all'){return [...(rows||[])].filter(r=>m==='all'||r.type===m).sort((a,b)=>(n(b.score)||0)-(n(a.score)||0))}
function top(rows,m='all',k=10){return ranked(rows,m).slice(0,k)}
function currentMarket(){return document.querySelector('.t10Tab.active')?.dataset?.market||market||'all'}
function prevSnapshot(){const h=hist();return h.length>1?h[h.length-2]:null}
function lastSnapshot(){const h=hist();return h.length?h[h.length-1]:null}
function prevRank(symbol,m){const p=prevSnapshot();if(!p)return null;const a=ranked(p.rows,m);const i=a.findIndex(x=>x.symbol===symbol);return i<0?null:i+1}
function prevRow(symbol){return prevSnapshot()?.rows?.find(x=>x.symbol===symbol)||null}
function momentum(row,rank,m){const pr=prevRank(row.symbol,m),old=prevRow(row.symbol),sd=old&&n(old.score)!=null?Number(row.score)-Number(old.score):0;let v=sd*4;if(pr==null||pr>10)v+=18;else v+=(pr-rank)*6;return Math.round(v*10)/10}
function tfSnap(r){const f=[['15M',r?.t15],['1H',r?.t1],['4H',r?.t4],['1D',r?.td],['1W',r?.tw]];return f.map(([name,x])=>({name,bias:n(x?.bias),rsi:n(x?.rsi),adx:n(x?.adx),vr:n(x?.volumeRatio??x?.volRatio)}))}
function methodMap(methods){const o={};for(const m of methods||[])o[m.name]={score:n(m.score),confidence:n(m.confidence),position:m.position||''};return o}
function calcRR(r,row){const rr=n(r?.v79?.rr?.rr1);if(rr!=null&&rr>0)return rr;const p=n(row.price)||n(r?.price),lv=r?.levels||{};const stop=n(lv.stop??lv.invalidate??lv.invalidation),t1=n(lv.target1??lv.tp1);if(!p||!stop||!t1||p===stop)return null;return Math.abs((t1-p)/(p-stop))}
function updateMethodPerf(symbol,price,methods){if(!symbol||!price||!methods)return;const P=perf(),s=P[symbol]||{last:null,methods:{}};if(s.last?.price&&s.last?.methods){const ret=(price-s.last.price)/s.last.price;for(const [name,m] of Object.entries(s.last.methods)){const sc=n(m.score);if(sc==null||Math.abs(sc-50)<10)continue;const dir=sc>=60?1:sc<=40?-1:0;if(!dir)continue;const hit=ret*dir>0,x=s.methods[name]||{n:0,w:0};x.n++;if(hit)x.w++;s.methods[name]=x}}s.last={ts:Date.now(),price,methods};P[symbol]=s;save(PERF_KEY,P)}
function adaptiveBonus(symbol,methods){const p=perf()[symbol]?.methods||{};let sum=0,w=0,used=[];for(const m of methods||[]){const x=p[m.name];if(!x||x.n<5)continue;const wr=x.w/x.n,edge=(wr-.5)*20,dir=(n(m.score)-50)/50;sum+=edge*dir;w++;used.push(`${m.name} ${Math.round(wr*100)}%/${x.n}`)}return {bonus:w?Math.max(-6,Math.min(6,sum/w)):0,used}}
function trapCheck(row,r,rr){const reasons=[];const dir=row.direction||((row.long||0)>=(row.short||0)?'LONG':'SHORT');const rsi4=n(r?.t4?.rsi),vr=n(r?.t4?.volumeRatio??r?.t4?.volRatio),state=String(r?.v79?.state||row.location||'');if(rr!=null&&rr<1.5)reasons.push(`R:R ${rr.toFixed(2)} < 1.5`);if((row.consensus||0)<55)reasons.push('전략 합의도 낮음');if((row.wait||0)>55)reasons.push('관망 위험 높음');if(dir==='LONG'&&rsi4!=null&&rsi4>=74)reasons.push(`4H RSI ${rsi4.toFixed(0)} 과열`);if(dir==='SHORT'&&rsi4!=null&&rsi4<=30)reasons.push(`4H RSI ${rsi4.toFixed(0)} 과매도`);if(/과열|추격/.test(state))reasons.push('추격 위험 상태');if(vr!=null&&vr<.75)reasons.push(`거래량 ${vr.toFixed(2)}× 약함`);return reasons}
function tfAgree(row,tfs){const dir=row.direction==='SHORT'?-1:row.direction==='LONG'?1:0;if(!dir)return {score:0,text:'방향 대기',core:false};const usable=tfs.filter(x=>x.bias!=null),same=usable.filter(x=>Math.sign(x.bias)===dir).length,score=usable.length?Math.round(same/usable.length*100):0;const map=Object.fromEntries(tfs.map(x=>[x.name,x.bias]));const core=['1H','4H','1D'].every(k=>map[k]!=null&&Math.sign(map[k])===dir);return {score,text:`${same}/${usable.length} 정렬`,core}}
function trigger(row,rr,tf,trap){if(row.direction==='WAIT')return {state:'관망',ok:false};if(trap.length>=2)return {state:'함정 경고 · 진입 보류',ok:false};if(rr!=null&&rr<1.5)return {state:'손익비 부족 · 대기',ok:false};if((row.confidence||0)>=72&&(row.consensus||0)>=60&&tf.core&&(rr==null||rr>=1.5))return {state:'진입 가능',ok:true};if((row.score||0)>=75&&tf.score>=60)return {state:row.direction==='LONG'?'눌림/재돌파 대기':'반등/재하락 대기',ok:false};return {state:'추가 확인 대기',ok:false}}
function grade(row,rr,tf,trap,mom,adapt){let s=n(row.score)||0;s+=(rr!=null?(rr>=2.5?6:rr>=2?4:rr>=1.5?1:-7):0);s+=(tf.core?5:tf.score>=60?2:-3);s+=Math.max(-5,Math.min(5,mom/6));s-=trap.length*3;s+=adapt.bonus;s=clamp(s);const g=s>=88?'S':s>=80?'A':s>=68?'B':'C';return {score:s,grade:g}}
function rrScore(rr){if(rr==null)return 50;if(rr>=3)return 100;if(rr>=2.5)return 92;if(rr>=2)return 82;if(rr>=1.5)return 68;if(rr>=1)return 42;return Math.max(5,Math.round(rr*35))}
function entryScore(row,x){let s=(x.grade?.score||0)*.40+(row.confidence||0)*.15+(row.consensus||0)*.15+(x.tf?.score||0)*.12+rrScore(x.rr)*.18;if(x.trigger?.ok)s+=8;if((row.wait||0)>55)s-=7;if(x.rr!=null&&x.rr<1.5)s-=14;s-=Math.min(28,(x.trap?.length||0)*9);return clamp(s)}
function explain(row,x){const a=[];if(x.mom>=12)a.push(`순위/적합도 급상승 ${x.mom>0?'+':''}${x.mom}`);if(x.rr!=null)a.push(`R:R ${x.rr.toFixed(2)}`);a.push(`시간봉 ${x.tf.text}`);if((row.consensus||0)>=65)a.push(`전략합의 ${row.consensus}%`);if((row.confidence||0)>=75)a.push(`신뢰 ${row.confidence}%`);if(x.adapt.used.length)a.push(`학습보정 ${x.adapt.bonus>=0?'+':''}${x.adapt.bonus.toFixed(1)}`);if(x.trap.length)a.push(`주의 ${x.trap[0]}`);return a.slice(0,4).join(' · ')}
async function enrichOne(row){const key=`${row.type}:${row.symbol}`,cache=enrichCache(),hit=cache[key];if(hit&&Date.now()-hit.ts<TTL&&hit.baseScore===row.score)return hit;const before=localStorage.getItem('v832learning');let r=null;try{r=await window.analyzeScannerSymbol(row.symbol,row.type)}finally{if(before==null)localStorage.removeItem('v832learning');else localStorage.setItem('v832learning',before)}const am=window.BTCStrategyPosition?.analyzeMethods?.(r),methods=am?.methods||[],mm=methodMap(methods),price=n(r?.price)||n(row.price);updateMethodPerf(row.symbol,price,mm);const tfs=tfSnap(r),rr=calcRR(r,row),tf=tfAgree(row,tfs),adapt=adaptiveBonus(row.symbol,methods),rank=ranked(auto()?.rows,currentMarket()).findIndex(x=>x.symbol===row.symbol)+1,mom=momentum(row,rank||99,currentMarket()),trap=trapCheck(row,r,rr),trig=trigger(row,rr,tf,trap),g=grade(row,rr,tf,trap,mom,adapt);const out={ts:Date.now(),baseScore:row.score,symbol:row.symbol,type:row.type,price,rr,tfs,tf,methods:mm,mom,trap,trigger:trig,grade:g,adaptive:adapt,why:explain(row,{rr,tf,mom,trap,adapt}),rsi4:n(r?.t4?.rsi),vr4:n(r?.t4?.volumeRatio??r?.t4?.volRatio)};cache[key]=out;save(ENRICH_KEY,cache);return out}
function alertEnabled(){return localStorage.getItem(ALERT_KEY)==='1'}
async function enableAlerts(){if(!('Notification'in window)){alert('이 브라우저는 알림을 지원하지 않습니다.');return}const p=await Notification.requestPermission();if(p==='granted'){localStorage.setItem(ALERT_KEY,'1');render();new Notification('기회 레이더 알림 켜짐',{body:'함정 없는 S/A급 신규진입·급상승·진입가능 변화만 알려드립니다.',icon:'icon-192.png'})}}
function maybeNotify(row,x,oppRank,actualRank){if(!alertEnabled()||!('Notification'in window)||Notification.permission!=='granted'||x.trap?.length)return;const prev=prevRank(row.symbol,currentMarket()),isNew=prev==null||prev>10,up=prev!=null?prev-oppRank:0,key=`btc_opp_notified_${lastSnapshot()?.sourceTs||0}_${row.symbol}`;if(localStorage.getItem(key))return;const reasons=[];if(isNew&&x.grade.score>=80)reasons.push('신규 TOP10');if(up>=3&&x.grade.score>=78)reasons.push(`순위 +${up}`);if(x.trigger.ok&&x.grade.score>=80)reasons.push('진입 가능');if(!reasons.length)return;localStorage.setItem(key,'1');try{new Notification(`${x.grade.grade}급 기회 · ${row.name||row.symbol}`,{body:`${reasons.join(' · ')} | 기회 #${oppRank} · 진입 #${actualRank} · ${row.direction}${x.rr!=null?` · R:R ${x.rr.toFixed(2)}`:''}`,icon:'icon-192.png'})}catch(e){}}
function css(){if($('oppV2Style'))return;const s=document.createElement('style');s.id='oppV2Style';s.textContent=`
#oppV2{margin:0 0 10px;padding:12px;border:1px solid #375e88;border-radius:15px;background:linear-gradient(180deg,#11243a,#0c1722)}.oppHead{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.oppTitle{font-size:16px;font-weight:900}.oppSmall{font-size:10px;color:#91a0b0;line-height:1.5}.oppTabs{display:flex;gap:5px;overflow:auto;margin:9px 0}.oppTabs button{white-space:nowrap;padding:7px 9px}.oppTabs button.active{background:#2767df}.oppGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.oppCard{padding:9px;border:1px solid #2c4156;border-radius:11px;background:#0a141e}.oppMain{background:transparent;border:0;padding:0;text-align:left;width:100%;color:inherit}.oppCard b{font-size:12px}.oppBadge{display:inline-block;margin-left:5px;padding:2px 5px;border-radius:999px;border:1px solid #43566d;font-size:9px}.oppS{color:#35e6a1}.oppA{color:#7fe6c0}.oppB{color:#ffd27f}.oppC{color:#ff8d9d}.oppGood{color:#20d792}.oppBad{color:#ff667a}.oppWarn{color:#ffbf47}.oppWhy{font-size:9px;color:#96a7b8;line-height:1.45;margin-top:4px}.oppCtl{display:flex;gap:6px;flex-wrap:wrap}.oppCtl button{padding:7px 9px}.oppSummary{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0}.oppChip{font-size:9px;border:1px solid #354a60;border-radius:999px;padding:3px 6px;color:#b1c0d0}.oppRanks{display:flex;gap:5px;flex-wrap:wrap;margin:5px 0}.oppRankChip{font-size:9px;border:1px solid #35506d;border-radius:999px;padding:2px 6px}.oppTrapToggle{margin-top:6px;padding:5px 7px;font-size:9px;background:#25171b;border-color:#6a3541;color:#ff9cac}.oppTrapDetail{margin-top:6px;padding:8px;border:1px solid #5f3440;border-radius:9px;background:#1d1216;font-size:9px;line-height:1.55;color:#e9b8c0}.oppTrapDetail[hidden]{display:none}.oppFactor{display:flex;justify-content:space-between;gap:8px;border-bottom:1px solid #322029;padding:3px 0}.oppFactor:last-child{border-bottom:0}@media(max-width:700px){.oppGrid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function host(){const page=$('top10Radar');if(!page)return null;css();let h=$('oppV2');if(h)return h;h=document.createElement('section');h.id='oppV2';const grid=page.querySelector('.t10Grid');if(grid)grid.parentNode.insertBefore(h,grid);else page.appendChild(h);return h}
function trapDetail(row,x){if(!x.trap?.length)return '';const rr=x.rr==null?'--':x.rr.toFixed(2),vr=x.vr4==null?'--':x.vr4.toFixed(2)+'×',rsi=x.rsi4==null?'--':x.rsi4.toFixed(0);return `<button class="oppTrapToggle" type="button">⚠ 함정 사유 ${x.trap.length}개 보기</button><div class="oppTrapDetail" hidden>${x.trap.map(v=>`<div>• ${esc(v)}</div>`).join('')}<div style="margin-top:6px"><div class="oppFactor"><span>R:R</span><b class="${x.rr!=null&&x.rr<1.5?'oppBad':'oppGood'}">${rr}</b></div><div class="oppFactor"><span>시간봉 정렬</span><b>${esc(x.tf.text)}${x.tf.core?' · 핵심정렬':''}</b></div><div class="oppFactor"><span>전략 합의</span><b>${row.consensus||0}%</b></div><div class="oppFactor"><span>신뢰도</span><b>${row.confidence||0}%</b></div><div class="oppFactor"><span>4H RSI / 거래량</span><b>${rsi} / ${vr}</b></div></div><div style="margin-top:6px"><b>결론:</b> 방향성 점수와 별개로 현재 진입가격의 손익비·과열·수급 조건이 불리하여 진입을 보류합니다.</div></div>`}
function rowCard(z){const {row,x,oppRank,actualRank}=z,gc='opp'+x.grade.grade,tc=x.trigger.ok?'oppGood':x.trap.length?'oppBad':'oppWarn';return `<div class="oppCard"><button class="oppMain" data-sym="${esc(row.symbol)}" data-type="${esc(row.type)}"><b>${esc(row.name||row.symbol)} <span class="oppBadge ${gc}">${x.grade.grade} ${x.grade.score}</span></b><div class="oppRanks"><span class="oppRankChip">기회 #${oppRank}</span><span class="oppRankChip">실제진입 #${actualRank}</span><span class="oppRankChip">진입점수 ${x.entryScore}</span></div><div class="oppSmall">${esc(row.direction)} · <span class="${tc}">${esc(x.trigger.state)}</span>${x.rr!=null?` · R:R ${x.rr.toFixed(2)}`:''}</div><div class="oppWhy">${esc(x.why||'분석 중')}</div></button>${trapDetail(row,x)}</div>`}
function buildItems(rows){const c=enrichCache(),base=rows.map((row,i)=>({row,x:c[`${row.type}:${row.symbol}`],oppRank:i+1})).filter(z=>z.x);for(const z of base)z.x.entryScore=entryScore(z.row,z.x);const actual=[...base].sort((a,b)=>b.x.entryScore-a.x.entryScore);actual.forEach((z,i)=>z.actualRank=i+1);return base}
function categoryRows(items,cat){if(cat==='actual')return [...items].sort((a,b)=>a.actualRank-b.actualRank);if(cat==='surge')return items.filter(x=>x.x.mom>=8).sort((a,b)=>b.x.mom-a.x.mom);if(cat==='entry')return items.filter(x=>x.x.trigger.ok).sort((a,b)=>a.actualRank-b.actualRank);if(cat==='wait')return items.filter(x=>/대기/.test(x.x.trigger.state)&&!x.x.trap.length).sort((a,b)=>a.actualRank-b.actualRank);if(cat==='trap')return items.filter(x=>x.x.trap.length).sort((a,b)=>b.x.trap.length-a.x.trap.length);if(cat==='short')return items.filter(x=>x.row.direction==='SHORT').sort((a,b)=>a.actualRank-b.actualRank);return [...items].sort((a,b)=>a.oppRank-b.oppRank)}
async function render(cat='all'){const h=host();if(!h)return;market=currentMarket();const A=auto();if(!A?.rows?.length){h.innerHTML='<div class="oppTitle">🔥 기회 레이더 V2.1</div><div class="oppSmall">AUTO TOP10 분석 결과가 쌓이면 정밀 기회 레이더가 작동합니다.</div>';return}h.innerHTML=`<div class="oppHead"><div><div class="oppTitle">🔥 기회 레이더 V2.1 <span class="oppBadge">${marketLabel(market)}</span></div><div class="oppSmall">종합기회순위와 실제진입순위를 분리하고, 함정 경고의 구체적 사유를 펼쳐볼 수 있습니다.</div></div><div class="oppCtl"><button id="oppRefresh">정밀 재분석</button><button id="oppAlert">${alertEnabled()?'알림 ON':'알림 켜기'}</button></div></div><div class="oppTabs"><button data-cat="all" class="${cat==='all'?'active':''}">🏆 종합기회</button><button data-cat="actual" class="${cat==='actual'?'active':''}">🎯 실제진입</button><button data-cat="surge" class="${cat==='surge'?'active':''}">🚀 급부상</button><button data-cat="entry" class="${cat==='entry'?'active':''}">✅ 진입가능</button><button data-cat="wait" class="${cat==='wait'?'active':''}">⏳ 대기</button><button data-cat="trap" class="${cat==='trap'?'active':''}">⚠ 함정</button><button data-cat="short" class="${cat==='short'?'active':''}">🔻 SHORT</button></div><div id="oppSummary" class="oppSummary"><span class="oppChip">정밀분석 준비 중...</span></div><div id="oppGrid" class="oppGrid"></div>`;$('oppRefresh')?.addEventListener('click',()=>refresh(true,cat));$('oppAlert')?.addEventListener('click',enableAlerts);h.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>paintFromCache(b.dataset.cat)));await refresh(false,cat)}
function paintItems(items,cat){const g=$('oppGrid'),s=$('oppSummary');if(!g)return;const show=categoryRows([...items],cat).slice(0,5);g.innerHTML=show.length?show.map(rowCard).join(''):'<div class="oppSmall">해당 조건의 종목이 없습니다.</div>';g.querySelectorAll('.oppMain').forEach(b=>b.addEventListener('click',()=>window.BTCStrategyPosition?.open?.(b.dataset.sym,b.dataset.type)));g.querySelectorAll('.oppTrapToggle').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const d=b.nextElementSibling;if(d){d.hidden=!d.hidden;b.textContent=d.hidden?`⚠ 함정 사유 보기`:`⚠ 함정 사유 닫기`}}));const sc=items.filter(z=>z.x.grade.grade==='S').length,ac=items.filter(z=>z.x.grade.grade==='A').length,en=items.filter(z=>z.x.trigger.ok).length,tr=items.filter(z=>z.x.trap.length).length,topActual=[...items].sort((a,b)=>a.actualRank-b.actualRank)[0];if(s)s.innerHTML=`<span class="oppChip">S ${sc}</span><span class="oppChip">A ${ac}</span><span class="oppChip">진입가능 ${en}</span><span class="oppChip">함정경고 ${tr}</span>${topActual?`<span class="oppChip">실제진입 1위 ${esc(topActual.row.name||topActual.row.symbol)}</span>`:''}<span class="oppChip">전략학습 ${Object.keys(perf()).length}종목</span>`;for(const z of items)maybeNotify(z.row,z.x,z.oppRank,z.actualRank)}
function paintFromCache(cat='all'){const A=auto();if(!A?.rows)return;paintItems(buildItems(top(A.rows,currentMarket(),10)),cat)}
async function refresh(force=false,cat='all'){if(running)return;const A=auto();if(!A?.rows)return;const rows=top(A.rows,currentMarket(),10),cache=enrichCache(),need=rows.filter(r=>force||!cache[`${r.type}:${r.symbol}`]||Date.now()-cache[`${r.type}:${r.symbol}`].ts>TTL||cache[`${r.type}:${r.symbol}`].baseScore!==r.score);if(!need.length){paintItems(buildItems(rows),cat);return}running=true;const s=$('oppSummary');if(s)s.innerHTML=`<span class="oppChip">정밀분석 0/${need.length}</span>`;let cursor=0,done=0;async function worker(){while(true){const i=cursor++;if(i>=need.length)return;try{await enrichOne(need[i])}catch(e){}done++;if(s)s.innerHTML=`<span class="oppChip">정밀분석 ${done}/${need.length}</span>`}}await Promise.all([worker(),worker()]);running=false;paintItems(buildItems(rows),cat)}
function boot(){css();setInterval(()=>{if($('top10Radar')){const m=currentMarket();if(m!==market){market=m;render()}}},1500);new MutationObserver(()=>{if($('top10Radar')&&!$('oppV2'))setTimeout(()=>render(),100)}).observe(document.body,{childList:true,subtree:true});if($('top10Radar'))render();window.BTCOpportunityV2={render,refresh,perf:()=>perf(),version:VERSION}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1800),{once:true});else setTimeout(boot,1800);
})();