/* BTC Hedge Assistant v8.15.0 - Adaptive Recovery + learned guard */
(()=>{'use strict';
const V='8.15.0',K='btc_recovery_v8130',$=id=>document.getElementById(id),N=v=>Number.isFinite(Number(v))?Number(v):null;
const HARD=10000,BOOST=12000,SAFE=15000;
function P(){try{return typeof pos==='function'?pos():(window.pos?.())}catch(e){return null}}
function M(){try{return typeof market!=='undefined'?market:(window.market||{})}catch(e){return window.market||{}}}
function px(){return Number(M()?.price)||Number((M()?.h4||[]).at(-1)?.[4])||0}
function state(){try{return JSON.parse(localStorage.getItem(K)||'null')||{}}catch(e){return{}}} function save(x){try{localStorage.setItem(K,JSON.stringify(x))}catch(e){}}
function fee(d){return(N(d.feeRate)||.04)/100} function closeWallet(d,p){return(N(d.wallet)||0)+(N(d.added)||0)+d.lq*(p-d.le)+d.sq*(d.se-p)-p*(d.lq+d.sq)*fee(d)}
function mmr(d){if(!d.liq||(!d.lq&&!d.sq))return null;const q=(N(d.wallet)||0)+(N(d.added)||0)+d.lq*(d.liq-d.le)+d.sq*(d.se-d.liq),n=(d.lq+d.sq)*d.liq;return n?q/n:null}
function liqFor(s,d,m){if(m==null)return NaN;const den=(s.lq-s.sq)-m*(s.lq+s.sq),num=s.wallet+s.added-s.lq*d.le+s.sq*d.se;return Math.abs(den)<1e-10?NaN:-num/den} function dist(s,d,m,p){const l=liqFor(s,d,m);return(!Number.isFinite(l)||l<=0)?1e12:Math.abs(l-p)}
function cs(s,d,p,q){q=Math.min(q,s.sq);return{...s,wallet:s.wallet+(d.se-p)*q-p*q*fee(d),sq:s.sq-q}} function cl(s,d,p,q){q=Math.min(q,s.lq);return{...s,wallet:s.wallet+(p-d.le)*q-p*q*fee(d),lq:s.lq-q}} function finalW(s,d,p){return s.wallet+s.added+s.lq*(p-d.le)+s.sq*(d.se-p)-p*(s.lq+s.sq)*fee(d)}
function maxTrim(s,d,m,p,side,need){const qty=side==='S'?s.sq:s.lq,fn=side==='S'?cs:cl;let best=0;for(let i=0;i<=120;i++){const q=qty*i/120,ns=fn(s,d,p,q);if(ns.wallet>=0&&dist(ns,d,m,p)>=need)best=q}return best}
function simDir(d,p0,dir,profile){const m=mmr(d),stepP=profile.stepPrice,limit=dir==='UP'?Math.max(150000,p0+70000):5000;let s={wallet:N(d.wallet)||0,added:N(d.added)||0,lq:d.lq,sq:d.sq},rows=[];if(m==null)return null;for(let p=dir==='UP'?Math.ceil(p0/stepP)*stepP:Math.floor(p0/stepP)*stepP;dir==='UP'?p<=limit:p>=limit;p+=dir==='UP'?stepP:-stepP){const side=dir==='UP'?'S':'L',q=Math.min(profile.stepQty,maxTrim(s,d,m,p,side,profile.buffer));if(q>1e-8)s=side==='S'?cs(s,d,p,q):cl(s,d,p,q);rows.push({p,w:finalW(s,d,p),safe:dist(s,d,m,p)})}return rows}
function firstHit(a,t){return a?.find(x=>x.w>=t)||null} function maxRow(a){return a?.reduce((b,x)=>!b||x.w>b.w?x:b,null)||null} function score(){try{return window.BTCRegimeHedge?.trendScore?.()?.score??50}catch(e){return 50}}
function learned(){try{return window.BTCAdaptiveLearning?.recommendation?.()||null}catch(e){return null}}
function profileFor(sc){const base=(sc>=85||sc<=15)?{name:'RECOVERY BOOST',buffer:BOOST,stepQty:.05,stepPrice:1000}:{name:'SAFE TREND',buffer:SAFE,stepQty:.04,stepPrice:2000},a=learned();if(a?.guard)base.buffer=Math.max(base.buffer,a.guard);base.learn=a;return base}
function pane(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function ensure(){let c=$('recoveryEngineCard');if(!c){c=document.createElement('div');c.id='recoveryEngineCard';c.className='card btcRecoveryCard'}const p=pane();if(p&&c.parentElement!==p){const q=$('v853HomeQuick');if(q&&q.parentElement===p)p.insertBefore(c,q);else p.appendChild(c)}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.display='block';c.style.width='100%';c.style.maxWidth='100%';c.style.marginLeft='0';c.style.marginRight='0';return c}
const money=x=>Number.isFinite(x)?'$'+Math.round(x).toLocaleString():'--';
function render(){const c=ensure(),d=P(),p=px();if(!c)return;if(!d?.lq||!d?.sq||!p){c.innerHTML=`<div class="row"><b>🎯 Adaptive Recovery + 10K Guard</b><span class="badge">v${V}</span></div><div class="small">포지션/시장 데이터 대기 중...</div>`;return}let st=state();if(!st.target)st.target=N(d.wallet)||69936.30;const now=closeWallet(d,p),sc=score(),pf=profileFor(sc),reg=sc>=72?'BULL':sc<=28?'BEAR':'TRANSITION';st.peakClose=Math.max(N(st.peakClose)||now,now);const recovered=now>=st.target,lock=recovered?Math.max(st.target,st.peakClose*.90):null;save(st);const up=simDir(d,p,'UP',pf),dn=simDir(d,p,'DOWN',pf),uh=firstHit(up,st.target),dh=firstHit(dn,st.target),best=[maxRow(up),maxRow(dn)].filter(Boolean).sort((a,b)=>b.w-a.w)[0],m=mmr(d),cur={wallet:N(d.wallet)||0,added:N(d.added)||0,lq:d.lq,sq:d.sq},curSafe=dist(cur,d,m,p);let action='전환장: 롱·숏 유지, 추가 축소 금지';if(reg==='BULL'){const q=Math.min(pf.stepQty,maxTrim(cur,d,m,p,'S',pf.buffer));action=q>1e-8?`상승장: 숏 최대 ${q.toFixed(3)} BTC 축소 후보 · 가드 ${Math.round(pf.buffer/1000)}K 이상`:'상승장이나 안전거리 조건상 숏 축소 대기'}else if(reg==='BEAR'){const q=Math.min(pf.stepQty,maxTrim(cur,d,m,p,'L',pf.buffer));action=q>1e-8?`하락장: 롱 최대 ${q.toFixed(3)} BTC 축소 후보 · 가드 ${Math.round(pf.buffer/1000)}K 이상`:'하락장이나 안전거리 조건상 롱 축소 대기'}if(curSafe<HARD)action='⛔ 10K 절대 방어선 미만: 추세매매 금지';if(recovered)action=`✅ 목표잔고 회복권: Recovery Lock 우선 · ${money(lock)}`;const prog=Math.max(0,Math.min(100,now/st.target*100)),learnTxt=pf.learn?`학습 권장 롱 ${(pf.learn.longKeep*100).toFixed(0)}% / 숏 ${(pf.learn.shortKeep*100).toFixed(0)}% · 학습가드 ${Math.round(pf.learn.guard/1000)}K`:'학습 엔진 대기';c.innerHTML=`<div class="row"><div><b>🎯 Adaptive Recovery + 10K Guard</b><div class="small">Wallet 회복 + 최대수익 후 양 포지션 종료</div></div><span class="badge">v${V}</span></div><div class="${recovered?'okbox':curSafe<HARD?'notice':'warnbox'}"><b>${reg} · ${pf.name}</b><br>${action}<div class="tiny" style="margin-top:5px">${learnTxt}</div></div><div class="grid2" style="margin-top:8px"><div class="kpi"><div class="small">현재 전량청산가치</div><b>${money(now)}</b><div class="tiny">회복률 ${prog.toFixed(1)}%</div></div><div class="kpi"><div class="small">목표 Wallet</div><b>${money(st.target)}</b></div><div class="kpi"><div class="small">청산가 안전거리</div><b>${money(curSafe)}</b><div class="tiny">절대 10K · 적용 ${Math.round(pf.buffer/1000)}K</div></div><div class="kpi"><div class="small">Recovery Lock</div><b>${lock?money(lock):'대기'}</b></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">상승 회복선</div><b>${uh?money(uh.p):'범위 밖'}</b></div><div class="kpi"><div class="small">하락 회복선</div><b>${dh?money(dh.p):'범위 밖'}</b></div><div class="kpi"><div class="small">시뮬레이션 최고</div><b>${best?money(best.w):'--'}</b></div></div>`}
function heal(){try{ensure();render()}catch(e){console.warn('Recovery heal',e)}} function boot(){heal();[300,700,1200,2200,4000,7000,11000].forEach(ms=>setTimeout(heal,ms));setInterval(heal,30000);new MutationObserver(()=>{const c=$('recoveryEngineCard');if(!c||!c.isConnected||c.parentElement!==pane())setTimeout(heal,50)}).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.BTCRecoveryEngine={version:V,render,simDir,closeWallet,mmr,heal};})();