/* Recovery Engine 2.0 UI */
(function(){'use strict';var data=null;
function $(x){return document.getElementById(x)}
function home(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function money(x){x=Number(x);return isFinite(x)?'$'+Math.round(x).toLocaleString():'--'}
function pct(x){x=Number(x);return isFinite(x)?(x*100).toFixed(1)+'%':'--'}
function regime(x){return({STRONG_UP:'강한 상승',UP:'상승',RANGE:'횡보',DOWN:'하락',CRASH_DOWN:'급락',UNKNOWN:'판정 대기'})[x]||x||'--'}
function ensure(){var p=home();if(!p)return null;var c=$('recoveryV2Card');if(!c){c=document.createElement('div');c.id='recoveryV2Card';c.className='card'}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.cssText='display:block!important;width:100%!important;max-width:100%!important;margin:0 0 10px!important';if(c.parentNode!==p){var a=$('researchShadowCard');if(a&&a.parentNode===p)p.insertBefore(c,a.nextSibling);else p.appendChild(c)}return c}
function render(){var c=ensure();if(!c)return;if(!data||!data.recovery2){c.innerHTML='<div class="row"><b>🧭 Recovery Engine 2.0</b><span class="badge">검증 중</span></div><div class="small">서버 Recovery/Regime/Shadow 2.0 데이터 대기 중...</div>';return}var r=data.recovery2,g=data.guard2||{},s=data.shadow2||{},rc=data.regimeChampion||{},gv=data.governance2||{};var ch=(rc.champions&&rc.champions[rc.current])||{};var tone=gv.promotionEligible?'okbox':'warnbox';c.innerHTML='<div class="row"><div><b>🧭 Recovery Engine 2.0</b><div class="small">회복 목적함수 · 장세별 Champion · Shadow 2.0 · Dynamic Guard</div></div><span class="badge">서버</span></div><div class="'+tone+'"><b>'+regime(rc.current)+' · '+(ch.name||gv.champion||'BASE')+'</b><br>Champion 승격 '+(gv.promotionEligible?'가능':'보류')+' · Active Forward '+(s.activeEvaluations||0)+'회 · 신뢰등급 <b>'+(s.confidenceGrade||'EXPERIMENT')+'</b></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">Wallet 회복률</div><b>'+pct(r.progress)+'</b><div class="tiny">'+money(r.currentNetClose)+' / '+money(r.targetWallet)+'</div></div><div class="kpi"><div class="small">Recovery 확률</div><b>'+pct(r.recoveryProbability)+'</b><div class="tiny">MC 기반</div></div><div class="kpi"><div class="small">Active 승률</div><b>'+(s.activeWinRate==null?'표본 대기':pct(s.activeWinRate))+'</b><div class="tiny">HOLD 제외</div></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">기대 Wallet</div><b>'+money(r.expectedWallet)+'</b></div><div class="kpi"><div class="small">P10 / Worst</div><b>'+money(r.p10Wallet)+'</b><div class="tiny">최악 '+money(r.worstWallet)+'</div></div><div class="kpi"><div class="small">Dynamic Guard</div><b>'+Math.round((g.dynamicOperatingGuardUsd||10000)/1000)+'K</b><div class="tiny">절대 하한 '+Math.round((g.hardFloorUsd||10000)/1000)+'K</div></div></div><div class="small" style="margin-top:8px">승격 기준: Active Forward 30회 + OOS + MDD + Worst-case 통과. 100회 VALIDATED, 300회 TRUSTED. 절대 10K Guard는 Optimizer가 해제할 수 없습니다.</div>'}
function refresh(){fetch('./data/research/latest.json?ts='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(x){data=x;render()}).catch(function(){render()})}
function boot(){ensure();refresh();[300,800,1500,3000,6000].forEach(function(ms){setTimeout(render,ms)});setInterval(refresh,60000);setInterval(render,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.BTCRecoveryV2={refresh:refresh,render:render};})();