/* Recovery Engine 2.0 UI - resilient loader + research position integrity */
(function(){'use strict';
var data=null,err='',lastOk=0,source='',attempt=0,$=function(x){return document.getElementById(x)};
function home(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function money(x){x=Number(x);return isFinite(x)?'$'+Math.round(x).toLocaleString():'--'}function pct(x){x=Number(x);return isFinite(x)?(x*100).toFixed(1)+'%':'--'}function regime(x){return({STRONG_UP:'강한 상승',UP:'상승',RANGE:'횡보',DOWN:'하락',CRASH_DOWN:'급락',UNKNOWN:'판정 대기'})[x]||x||'--'}function age(ts){if(!ts)return'--';var m=Math.max(0,(Date.now()-new Date(ts).getTime())/60000);return m<1?'방금':m<60?Math.round(m)+'분 전':(m/60).toFixed(1)+'시간 전'}
function ensure(){var p=home();if(!p)return null;var c=$('recoveryV2Card');if(!c){c=document.createElement('div');c.id='recoveryV2Card';c.className='card'}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.cssText='display:block!important;width:100%!important;max-width:100%!important;margin:0 0 10px!important';if(c.parentNode!==p){var a=$('researchShadowCard');if(a&&a.parentNode===p)p.insertBefore(c,a.nextSibling);else p.appendChild(c)}return c}
function valid(x){return !!(x&&x.recovery2&&x.guard2&&x.regimeChampion&&x.shadow2)}async function getJson(url){var r=await fetch(url,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}
async function refresh(){attempt++;var ts=Date.now(),urls=['./data/research/latest.json?recovery2='+ts,'/btc/data/research/latest.json?recovery2='+ts,'https://raw.githubusercontent.com/ztman000-bot/btc/main/data/research/latest.json?recovery2='+ts],errors=[];for(var i=0;i<urls.length;i++){try{var x=await getJson(urls[i]);if(!valid(x))throw new Error('Recovery 2.0 필드 없음');data=x;err='';source=i===0?'Pages relative':i===1?'Pages absolute':'GitHub raw fallback';lastOk=Date.now();render();document.dispatchEvent(new CustomEvent('btc-recovery2-ready',{detail:{engineVersion:x.engineVersion||'--',generatedAt:x.generatedAt||null,source:source}}));return x}catch(e){errors.push(String(e&&e.message||e))}}err=errors.join(' / ');render();return null}
function researchIntegrity(){try{return window.BTCSafetyCore?.status?.()||null}catch(e){return null}}
function render(){var c=ensure();if(!c)return;if(!valid(data)){c.innerHTML='<div class="row"><div><b>🧭 Recovery Engine 2.0</b><div class="small">서버 Recovery/Regime/Shadow 연결 확인</div></div><span class="badge">'+(err?'재시도 중':'검증 중')+'</span></div><div class="'+(err?'notice':'warnbox')+'"><b>'+(err?'데이터 로딩 재시도':'서버 데이터 확인 중')+'</b><br>'+(err?err:'최신 Recovery 2.0 데이터를 불러오는 중입니다.')+'</div><div class="tiny" style="margin-top:6px">시도 '+attempt+'회 · 기본 경로 실패 시 Pages 절대경로와 GitHub raw를 자동 확인합니다.</div>';return}
var r=data.recovery2,g=data.guard2||{},s=data.shadow2||{},rc=data.regimeChampion||{},gv=data.governance2||{},ch=(rc.champions&&rc.champions[rc.current])||{},si=researchIntegrity(),matched=si&&si.researchPositionKnown?si.researchPositionMatched:null,tone=gv.promotionEligible&&matched!==false?'okbox':'warnbox',integrity=matched===false?'<div class="notice" style="margin-top:8px"><b>⚠ 서버 MC 포지션 불일치</b><br>현재 앱 포지션과 data/research/config.json의 서버 연구 포지션이 다릅니다. 아래 MC/Recovery 수치는 참고용으로만 표시하며 실전 승격 근거로 사용하지 마세요.</div>':matched===true?'<div class="okbox" style="margin-top:8px"><b>✅ 서버 MC 포지션 일치 확인</b> · 현재 앱 포지션과 연구 스냅샷 일치</div>':'<div class="warnbox" style="margin-top:8px"><b>연구 포지션 대조 대기</b> · Safety Core가 config 스냅샷을 확인 중</div>';
c.innerHTML='<div class="row"><div><b>🧭 Recovery Engine 2.0</b><div class="small">회복 목적함수 · 독립 장세별 Champion · Confirmed 4H Shadow · Dynamic Guard</div></div><span class="badge">ENGINE '+(data.engineVersion||'--')+'</span></div>'+integrity+'<div class="'+tone+'"><b>'+regime(rc.current)+' · '+(ch.name||gv.champion||'BASE')+'</b><br>Champion 승격 '+(gv.promotionEligible&&matched!==false?'가능':'보류')+' · Independent Active Forward '+(s.activeEvaluations||0)+'회 · 신뢰등급 <b>'+(s.confidenceGrade||'EXPERIMENT')+'</b></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">Wallet 회복률</div><b>'+pct(r.progress)+'</b><div class="tiny">'+money(r.currentNetClose)+' / '+money(r.targetWallet)+'</div></div><div class="kpi"><div class="small">Recovery 확률</div><b>'+pct(r.recoveryProbability)+'</b><div class="tiny">서버 3000-path MC'+(matched===false?' · 참고용':'')+'</div></div><div class="kpi"><div class="small">Active 승률</div><b>'+(s.activeWinRate==null?'표본 대기':pct(s.activeWinRate))+'</b><div class="tiny">HOLD 제외 · 확정 4H만</div></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">기대 Wallet</div><b>'+money(r.expectedWallet)+'</b></div><div class="kpi"><div class="small">P10 / Worst</div><b>'+money(r.p10Wallet)+'</b><div class="tiny">최악 '+money(r.worstWallet)+'</div></div><div class="kpi"><div class="small">Dynamic Guard</div><b>'+Math.round((g.dynamicOperatingGuardUsd||10000)/1000)+'K</b><div class="tiny">절대 하한 '+Math.round((g.hardFloorUsd||10000)/1000)+'K</div></div></div><div class="tiny" style="margin-top:8px">Research Engine '+(data.engineVersion||'--')+' · 생성 '+age(data.generatedAt)+' · 로더 '+source+' · 마지막 성공 '+age(lastOk?new Date(lastOk).toISOString():null)+'</div><div class="small" style="margin-top:6px">Forward 증거는 새로 완결된 4H 봉에서만 1회 적립합니다. CANDIDATE 30 · VALIDATED 100 · TRUSTED 300. 절대 10K Guard는 어떤 Optimizer도 해제할 수 없습니다.</div>'}
function boot(){ensure();refresh();[1500,4000,9000,15000,30000].forEach(function(ms){setTimeout(function(){if(!valid(data))refresh();else render()},ms)});setInterval(refresh,60000);setInterval(render,5000);document.addEventListener('btc-safety-core',function(){setTimeout(render,30)})}
window.BTCRecoveryV2={refresh:refresh,render:render,status:function(){return{ready:valid(data),error:err,lastOk:lastOk,source:source,data:data}}};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();