/* BTC Hedge Assistant v8.20.0 - Adaptive Recovery + Central Safety Guard */
(()=>{'use strict';
const V='8.20.0',K='btc_recovery_v8130',$=id=>document.getElementById(id),N=v=>Number.isFinite(Number(v))?Number(v):null;const HARD=10000,BOOST=12000,SAFE=15000;
function P(){try{return typeof pos==='function'?pos():(window.pos?.())}catch(e){return null}}function M(){try{return typeof market!=='undefined'?market:(window.market||{})}catch(e){return window.market||{}}}function px(){return Number(M()?.price)||Number((M()?.h4||[]).at(-1)?.[4])||0}
function state(){try{return JSON.parse(localStorage.getItem(K)||'null')||{}}catch(e){return{}}}function save(x){try{localStorage.setItem(K,JSON.stringify(x))}catch(e){}}function fee(d){return(N(d.feeRate)||.04)/100}function closeWallet(d,p){return(N(d.wallet)||0)+(N(d.added)||0)+d.lq*(p-d.le)+d.sq*(d.se-p)-p*(d.lq+d.sq)*fee(d)}
function mmr(d){if(window.BTCSafetyCore?.mmr)return window.BTCSafetyCore.mmr(d);if(!d.liq||(!d.lq&&!d.sq))return null;const q=(N(d.wallet)||0)+(N(d.added)||0)+d.lq*(d.liq-d.le)+d.sq*(d.se-d.liq),n=(d.lq+d.sq)*d.liq;return n?q/n:null}function liqFor(s,d,m){if(window.BTCSafetyCore?.liqFor)return window.BTCSafetyCore.liqFor(s,d,m);if(m==null)return NaN;const den=(s.lq-s.sq)-m*(s.lq+s.sq),num=s.wallet+s.added-s.lq*d.le+s.sq*d.se;return Math.abs(den)<1e-10?NaN:-num/den}function dist(s,d,m,p){if(window.BTCSafetyCore?.distance)return window.BTCSafetyCore.distance(d,p,s);const l=liqFor(s,d,m);return(!Number.isFinite(l)||l<=0)?1e12:Math.abs(l-p)}
function cs(s,d,p,q){q=Math.min(q,s.sq);return{...s,wallet:s.wallet+(d.se-p)*q-p*q*fee(d),sq:s.sq-q}}function cl(s,d,p,q){q=Math.min(q,s.lq);return{...s,wallet:s.wallet+(p-d.le)*q-p*q*fee(d),lq:s.lq-q}}function finalW(s,d,p){return s.wallet+s.added+s.lq*(p-d.le)+s.sq*(d.se-p)-p*(s.lq+s.sq)*fee(d)}
function central(){try{return window.BTCSafetyCore?.current?.()||{hard:HARD,operating:SAFE,source:'LOCAL_SAFE'}}catch(e){return{hard:HARD,operating:SAFE,source:'LOCAL_SAFE'}}}function healthAllowed(){return window.BTC_DECISION_ALLOWED!==false&&!!window.BTCSafetyCore}
function maxTrim(s,d,m,p,side,need){const qty=side==='S'?s.sq:s.lq,fn=side==='S'?cs:cl;let best=0;for(let i=0;i<=120;i++){const q=qty*i/120,ns=fn(s,d,p,q);if(ns.wallet>=0&&dist(ns,d,m,p)>=need)best=q}return best}
function simDir(d,p0,dir,profile){const m=mmr(d),stepP=profile.stepPrice,limit=dir==='UP'?Math.max(150000,p0+70000):5000;let s={wallet:N(d.wallet)||0,added:N(d.added)||0,lq:d.lq,sq:d.sq},rows=[];if(m==null)return null;for(let p=dir==='UP'?Math.ceil(p0/stepP)*stepP:Math.floor(p0/stepP)*stepP;dir==='UP'?p<=limit:p>=limit;p+=dir==='UP'?stepP:-stepP){const side=dir==='UP'?'S':'L',q=Math.min(profile.stepQty,maxTrim(s,d,m,p,side,profile.buffer));if(q>1e-8)s=side==='S'?cs(s,d,p,q):cl(s,d,p,q);rows.push({p,w:finalW(s,d,p),safe:dist(s,d,m,p)})}return rows}
function firstHit(a,t){return a?.find(x=>x.w>=t)||null}function maxRow(a){return a?.reduce((b,x)=>!b||x.w>b.w?x:b,null)||null}function score(){try{return window.BTCRegimeHedge?.trendScore?.()?.score??50}catch(e){return 50}}function learned(){try{return window.BTCAdaptiveLearning?.recommendation?.()||null}catch(e){return null}}
function profileFor(sc){const base=(sc>=85||sc<=15)?{name:'RECOVERY BOOST',buffer:BOOST,stepQty:.05,stepPrice:1000}:{name:'SAFE TREND',buffer:SAFE,stepQty:.04,stepPrice:2000},a=learned(),g=central();base.buffer=Math.max(base.buffer,g.operating||HARD);if(a?.healthy&&a.guard)base.buffer=Math.max(base.buffer,a.guard);base.learn=a;base.central=g;return base}
function pane(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}function ensure(){let c=$('recoveryEngineCard');if(!c){c=document.createElement('div');c.id='recoveryEngineCard';c.className='card btcRecoveryCard'}const p=pane();if(p&&c.parentElement!==p){const q=$('v853HomeQuick');if(q&&q.parentElement===p)p.insertBefore(c,q);else p.appendChild(c)}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.cssText+=';display:block;width:100%;max-width:100%;min-width:0;margin-left:0;margin-right:0';return c}const money=x=>Number.isFinite(x)?'$'+Math.round(x).toLocaleString():'--';
function render(){const c=ensure(),d=P(),p=px();if(!c)return;if(!d?.lq||!d?.sq||!p){c.innerHTML=`<div class="row"><b>🎯 Adaptive Recovery + Central Guard</b><span class="badge">v${V}</span></div><div class="small">포지션/시장 데이터 대기 중...</div>`;return}let st=state();if(!st.target)st.target=N(d.wallet)||69936.30;const now=closeWallet(d,p),sc=score(),pf=profileFor(sc),reg=sc>=72?'BULL':sc<=28?'BEAR':'TRANSITION';st.peakClose=Math.max(N(st.peakClose)||now,now);const recovered=now>=st.target,lock=recovered?Math.max(st.target,st.peakClose*.90):null;save(st);const up=simDir(d,p,'UP',pf),dn=simDir(d,p,'DOWN',pf),uh=firstHit(up,st.target),dh=firstHit(dn,st.target),best=[maxRow(up),maxRow(dn)].filter(Boolean).sort((a,b)=>b.w-a.w)[0],m=mmr(d),cur={wallet:N(d.wallet)||0,added:N(d.added)||0,lq:d.lq,sq:d.sq},curSafe=dist(cur,d,m,p),centralG=pf.central,need=pf.buffer;let title='🟡 지금 할 일: 관망',action='실행조건을 기다리며 롱·숏 유지',tone='warnbox',q=0;
if(reg==='BULL'){q=Math.min(pf.stepQty,maxTrim(cur,d,m,p,'S',need));title='🟢 지금 할 일: 숏 축소 검토';action=q>1e-8?`조건 충족 시 숏 최대 ${q.toFixed(3)} BTC 축소 · 실행 후 ${Math.round(need/1000)}K 이상 유지`:'상승 우위지만 중앙 Guard 조건상 숏 축소 대기';tone='okbox'}else if(reg==='BEAR'){q=Math.min(pf.stepQty,maxTrim(cur,d,m,p,'L',need));title='🔴 지금 할 일: 롱 축소 검토';action=q>1e-8?`조건 충족 시 롱 최대 ${q.toFixed(3)} BTC 축소 · 실행 후 ${Math.round(need/1000)}K 이상 유지`:'하락 우위지만 중앙 Guard 조건상 롱 축소 대기';tone='notice'}
const learnedHold=pf.learn?.healthy&&/관망/.test(pf.learn.action?.title||'');if(learnedHold){title='🟡 지금 할 일: 관망';action='Optimizer는 방향 우위를 감지했지만 상단 실행조건 미충족 · 포지션 변경 없음';tone='warnbox';q=0}if(!healthAllowed()){title='⛔ 지금 할 일: 시스템 제한';action='Runtime Health 또는 Central Safety Core 미확인 · 포지션 변경 권고 금지';tone='notice';q=0}else if(curSafe<(centralG.hard||HARD)){title='⛔ 지금 할 일: 포지션 축소 중지';action='청산가 안전거리 10K 미만 · 추세매매 금지';tone='notice';q=0}else if(curSafe<need){title='🟡 지금 할 일: Guard 복구 우선';action=`현재 안전거리 ${money(curSafe)}가 운영 Guard ${money(need)}보다 작음 · 신규 추세 축소 금지`;tone='warnbox';q=0}if(recovered&&healthAllowed()){title='✅ 지금 할 일: 수익 잠금';action=`목표잔고 회복권 · Recovery Lock ${money(lock)} 아래로 반납하지 않는 것이 우선`;tone='okbox';q=0}
const prog=Math.max(0,Math.min(100,now/st.target*100));let learnTxt='Optimizer 연결 대기';if(pf.learn?.healthy){const ch=pf.learn.champion?.name||pf.learn.champion||'BASE';learnTxt=`✅ Optimizer 연결 · Champion ${ch} · 롱 ${(pf.learn.longKeep*100).toFixed(0)}% / 숏 ${(pf.learn.shortKeep*100).toFixed(0)}% · Adaptive ${Math.round(pf.learn.guard/1000)}K`}else if(pf.learn&&!pf.learn.healthy)learnTxt=`⚠ Optimizer 오류 · ${pf.learn.error||'확인 필요'}`;
c.innerHTML=`<div class="row"><div><b>🎯 Adaptive Recovery + Central Safety Guard</b><div class="small">Wallet 회복 + 최대수익 + 최종 양포지션 종료 · 공통 Fail-Safe</div></div><span class="badge">v${V}</span></div><div class="${tone}" style="margin-top:8px"><b style="font-size:19px">${title}</b><br>${action}<div class="tiny" style="margin-top:6px">${learnTxt}</div></div><div class="grid2" style="margin-top:8px"><div class="kpi"><div class="small">현재 전량청산가치</div><b>${money(now)}</b><div class="tiny">회복률 ${prog.toFixed(1)}%</div></div><div class="kpi"><div class="small">청산가 안전거리</div><b>${money(curSafe)}</b><div class="tiny">절대 ${Math.round((centralG.hard||HARD)/1000)}K · 운영 ${Math.round(need/1000)}K · ${centralG.source||'LOCAL'}</div></div></div><details style="margin-top:9px"><summary class="small"><b>회복 시뮬레이션 상세보기</b></summary><div class="grid2" style="margin-top:8px"><div class="kpi"><div class="small">목표 Wallet</div><b>${money(st.target)}</b></div><div class="kpi"><div class="small">Recovery Lock</div><b>${lock?money(lock):'대기'}</b></div><div class="kpi"><div class="small">상승 회복선</div><b>${uh?money(uh.p):'범위 밖'}</b></div><div class="kpi"><div class="small">하락 회복선</div><b>${dh?money(dh.p):'범위 밖'}</b></div><div class="kpi"><div class="small">시뮬레이션 최고</div><b>${best?money(best.w):'--'}</b></div></div></details>`}
function heal(){try{ensure();render()}catch(e){console.warn('Recovery heal',e)}}function boot(){heal();[300,700,1200,2200,4000,7000,11000].forEach(ms=>setTimeout(heal,ms));setInterval(heal,30000);document.addEventListener('btc-adaptive-ready',()=>setTimeout(heal,20));document.addEventListener('btc-system-health',()=>setTimeout(heal,20));document.addEventListener('btc-safety-core',()=>setTimeout(heal,20));new MutationObserver(()=>{const c=$('recoveryEngineCard');if(!c||!c.isConnected||c.parentElement!==pane())setTimeout(heal,50)}).observe(document.body,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.BTCRecoveryEngine={version:V,render,simDir,closeWallet,mmr,heal};})();