/* BTC Hedge Assistant v8.11.0 - Regime Switching Hedge Engine */
(()=>{'use strict';
const V='8.11.0', KEY='btc_regime_v8110';
const ROBUST={name:'ROBUST',bullLong:.65,bullShort:.60,bearLong:.50,bearShort:.60};
const CONS={name:'CONSERVATIVE',bullLong:.75,bullShort:.70,bearLong:.60,bearShort:.75};
const HOLD={name:'HOLD',bullLong:1,bullShort:1,bearLong:1,bearShort:1};
const $=id=>document.getElementById(id), num=v=>Number.isFinite(Number(v))?Number(v):null, clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function M(){try{return typeof market!=='undefined'?market:(window.market||{})}catch(e){return window.market||{}}}
function P(){try{return typeof pos==='function'?pos():(window.pos?.())}catch(e){return null}}
function rows(tf){const m=M(),a=m?.[tf]||[];return Array.isArray(a)?a:[]}
function closes(tf){return rows(tf).map(r=>Number(Array.isArray(r)?r[4]:(r.close??r.c))).filter(Number.isFinite)}
function ema(a,p){if(!a.length)return[];let e=a[0],k=2/(p+1);return a.map(v=>(e=v*k+e*(1-k)))}
function trendScore(){const h=closes('h4'),d=closes('d1');if(h.length<55||d.length<25)return null;const eh20=ema(h,20),eh50=ema(h,50),ed20=ema(d,20),ed50=ema(d,50),hc=h.at(-1),dc=d.at(-1);let s=50,why=[];const add=(cond,pts,label)=>{s+=cond?pts:-pts;why.push(`${cond?'✓':'·'} ${label}`)};add(hc>eh20.at(-1),7,'4H 가격>EMA20');add(eh20.at(-1)>eh50.at(-1),8,'4H EMA20>EMA50');add(eh20.at(-1)>eh20.at(-4),6,'4H EMA20 상승');add(dc>ed20.at(-1),8,'1D 가격>EMA20');add(ed20.at(-1)>ed50.at(-1),9,'1D EMA20>EMA50');add(ed20.at(-1)>ed20.at(-4),7,'1D EMA20 상승');const h12=h.slice(-13),d10=d.slice(-11);add(hc>Math.max(...h12.slice(0,-1)),3,'4H 최근 고점 돌파');add(dc>Math.max(...d10.slice(0,-1)),2,'1D 최근 고점 돌파');return{score:clamp(Math.round(s),0,100),why,h,d,hc,dc}}
function loadState(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{regime:'TRANSITION'}}catch(e){return{regime:'TRANSITION'}}}
function saveState(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch(e){}}
function regimeOf(score){const old=loadState().regime||'TRANSITION';let r=old;if(old==='BULL'){if(score<58)r='TRANSITION'}else if(old==='BEAR'){if(score>42)r='TRANSITION'}else{if(score>=72)r='BULL';else if(score<=28)r='BEAR'};saveState({regime:r,score,at:Date.now()});return r}
function equity(p,d,lq,sq,real,fees){return(num(d.wallet)||0)+(num(d.added)||0)+real-fees+lq*(p-d.le)+sq*(d.se-p)}
function closeL(p,q,d,s){if(q<=0)return;s.real+=(p-d.le)*q;s.fees+=p*q*s.fee;s.lq-=q}
function closeS(p,q,d,s){if(q<=0)return;s.real+=(d.se-p)*q;s.fees+=p*q*s.fee;s.sq-=q}
function dd(a){let pk=a[0]||0,m=0;for(const x of a){pk=Math.max(pk,x);m=Math.max(m,pk-x)}return m}
function sim(px,d,prof){if(!px?.length)return{end:0,mdd:0};let s={lq:d.lq,sq:d.sq,real:0,fees:0,fee:(num(d.feeRate)||.04)/100},e20=ema(px,20),e50=ema(px,50),bullN=0,bearN=0,mode='TRANSITION',bt=false,br=false,lt=false,st=false,eq=[];for(let i=0;i<px.length;i++){const p=px[i];if(i>3){const bull=p>e20[i]&&e20[i]>e50[i]&&e20[i]>e20[i-3],bear=p<e20[i]&&e20[i]<e50[i]&&e20[i]<e20[i-3];bullN=bull?bullN+1:0;bearN=bear?bearN+1:0;if(bullN>=3)mode='BULL';else if(bearN>=3)mode='BEAR';else if(!bull&&!bear)mode='TRANSITION'}if(mode==='BULL'){if(!bt){closeS(p,Math.max(0,s.sq-d.sq*prof.bullShort),d,s);bt=true}if(!lt&&p>=d.le*1.08){closeL(p,Math.max(0,s.lq-d.lq*prof.bullLong),d,s);lt=true}}else if(mode==='BEAR'){if(!br){closeL(p,Math.max(0,s.lq-d.lq*prof.bearLong),d,s);br=true}if(!st&&p<=d.se*.92){closeS(p,Math.max(0,s.sq-d.sq*prof.bearShort),d,s);st=true}}eq.push(equity(p,d,s.lq,s.sq,s.real,s.fees))}const p=px.at(-1);closeL(p,s.lq,d,s);closeS(p,s.sq,d,s);return{end:(num(d.wallet)||0)+(num(d.added)||0)+s.real-s.fees,mdd:dd(eq)}}
function histGuard(d){const a=closes('h4');if(a.length<120)return{profile:CONS,windows:0,note:'4H 표본 부족 → 보수형'};let winsR=0,winsC=0,scoreR=0,scoreC=0,n=0;for(let end=a.length;end>=120&&n<6;end-=48){const px=a.slice(Math.max(0,end-120),end);if(px.length<80)continue;const h=sim(px,d,HOLD),r=sim(px,d,ROBUST),c=sim(px,d,CONS);const rr=(r.end-h.end)-.30*r.mdd,cc=(c.end-h.end)-.30*c.mdd;scoreR+=rr;scoreC+=cc;if(rr>=cc)winsR++;else winsC++;n++}if(!n)return{profile:CONS,windows:0,note:'4H 검증구간 부족 → 보수형'};const useR=scoreR>=scoreC&&winsR>=Math.ceil(n/2);return{profile:useR?ROBUST:CONS,windows:n,winsR,winsC,scoreR:scoreR/n,scoreC:scoreC/n,note:useR?'최근 4H 위험조정 성과: 강건형 우세':'최근 4H 위험조정 성과: 보수형 우세'}}
function target(regime,score,prof){if(regime==='BULL'){const weak=score<85;return{longKeep:clamp(prof.bullLong+(weak?.10:.05),0,1),shortKeep:clamp(prof.bullShort+(weak?.10:0),0,1),baseLong:prof.bullLong,baseShort:prof.bullShort}}if(regime==='BEAR'){const weak=score>15;return{longKeep:clamp(prof.bearLong+(weak?.10:0),0,1),shortKeep:clamp(prof.bearShort+(weak?.15:.05),0,1),baseLong:prof.bearLong,baseShort:prof.bearShort}}return{longKeep:1,shortKeep:1,baseLong:1,baseShort:1}}
function makePath(nodes,bars=30){let out=[];for(let j=0;j<nodes.length-1;j++){const a=nodes[j],b=nodes[j+1];for(let z=0;z<bars;z++){const t=z/bars;out.push(a+(b-a)*t+Math.sin(t*Math.PI*4+j)*(a+(b-a)*t)*.006)}}out.push(nodes.at(-1));return out}
function stress(d,price,prof){const P0=price,paths={UP50:[P0,P0+50000],DOWN50:[P0,Math.max(5000,P0-50000)],UP30_DOWN50:[P0,P0+30000,Math.max(5000,P0-20000)],DOWN30_UP50:[P0,Math.max(5000,P0-30000),P0+20000]};let out={};for(const[k,nodes]of Object.entries(paths)){const px=makePath(nodes),hold=sim(px,d,HOLD),opt=sim(px,d,prof);out[k]={hold,opt,delta:opt.end-hold.end}}return out}
function ensure(){let c=$('regimeHedgeCard');if(c)return c;const anchor=$('cycleHedgeCard')||$('dynamicHedgeCard');if(!anchor)return null;c=document.createElement('div');c.id='regimeHedgeCard';c.className='card';anchor.insertAdjacentElement('afterend',c);return c}
const money=x=>Number.isFinite(x)?'$'+Math.round(x).toLocaleString():'--',q=x=>Number.isFinite(x)?x.toFixed(3):'--';
function render(){const c=ensure();if(!c)return;const d=P(),tr=trendScore();if(!d?.lq||!d?.sq||!tr){c.innerHTML='<b>🧭 장세분리 헤지 엔진</b><div class="small">포지션·4H·1D 데이터를 기다리는 중...</div>';return}const hg=histGuard(d),r=regimeOf(tr.score),t=target(r,tr.score,hg.profile),price=tr.hc,s=stress(d,price,hg.profile),conf=Math.round(Math.abs(tr.score-50)*2),trimL=Math.max(0,d.lq*(1-t.longKeep)),trimS=Math.max(0,d.sq*(1-t.shortKeep));let action=r==='BULL'?`상승장: 숏 ${q(trimS)} BTC 축소 후보 · 롱은 평단 위 수익화 후 최소 ${(t.longKeep*100).toFixed(0)}% 코어`:r==='BEAR'?`하락장: 롱 ${q(trimL)} BTC 축소 후보 · 숏은 수익구간에서 최소 ${(t.shortKeep*100).toFixed(0)}% 코어`:'전환장: 롱·숏 모두 유지, 방향 확인 전 추가 축소 금지';const cls=r==='BULL'?'okbox':r==='BEAR'?'notice':'warnbox',cell=(name,x)=>`<div class="kpi"><div class="small">${name}</div><b>${money(x.opt.end)}</b><div class="tiny">그대로 ${money(x.hold.end)} · 차이 ${x.delta>=0?'+':''}${money(x.delta).replace('$','')}</div></div>`;c.innerHTML=`<div class="row"><div><b>🧭 장세분리 Regime Hedge</b><div class="small">±50K + 반전 스트레스 + 최근 4H 재검증 · 자동주문 아님</div></div><span class="badge">v${V}</span></div><div class="${cls}"><b>${r} · 장세점수 ${tr.score}/100 · 신뢰 ${conf}%</b><br>${action}</div><div class="grid3"><div class="kpi"><div class="small">현재 권장 롱 유지</div><b>${(t.longKeep*100).toFixed(0)}%</b><div class="tiny">선택 기준 ${t.baseLong*100}%</div></div><div class="kpi"><div class="small">현재 권장 숏 유지</div><b>${(t.shortKeep*100).toFixed(0)}%</b><div class="tiny">선택 기준 ${t.baseShort*100}%</div></div><div class="kpi"><div class="small">4H 검증 프로필</div><b>${hg.profile.name}</b><div class="tiny">${hg.windows}구간 · R ${hg.winsR||0} / C ${hg.winsC||0}</div></div></div><div class="${hg.profile.name==='ROBUST'?'okbox':'warnbox'}"><b>${hg.note}</b><br>강건형 BULL 65/60 · BEAR 50/60 ｜ 보수형 BULL 75/70 · BEAR 60/75</div><div class="small" style="margin-top:9px"><b>현재가 기준 전량청산 Wallet 스트레스 비교</b></div><div class="grid4" style="margin-top:6px">${cell('+50K',s.UP50)}${cell('-50K',s.DOWN50)}${cell('+30K→-50K',s.UP30_DOWN50)}${cell('-30K→+50K',s.DOWN30_UP50)}</div><details style="margin-top:8px"><summary class="small">장세 판정 근거 보기</summary><div class="tiny" style="line-height:1.7;margin-top:6px">${tr.why.join('<br>')}</div></details><div class="notice">장세 전환 가드: BULL 진입 ≥72, BULL 종료 &lt;58 / BEAR 진입 ≤28, BEAR 종료 &gt;42. TRANSITION에서는 100/100 유지합니다. 최근 4H 위험조정 검증에서 강건형이 밀리면 자동으로 보수형 비율로 이동합니다.</div>`}
function boot(){let n=0,t=setInterval(()=>{render();if(++n>24)clearInterval(t)},900);setInterval(render,30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.BTCRegimeHedge={version:V,render,trendScore,target,stress,histGuard};})();