/* BTC Hedge Assistant v8.23.0 - Reliability Core */
(()=>{'use strict';
if(window.__BTC_RELIABILITY_CORE__&&window.BTCReliabilityCore)return;window.__BTC_RELIABILITY_CORE__=true;
const V='8.23.0',S={startedAt:Date.now(),lastCheck:0,lastPrice:null,lastPriceAt:0,staleSince:0,failClosed:false,reasons:[],checks:0,recoveries:0};
const cfg=()=>window.BTC_APP_CONFIG?.safety||{};
function n(v){v=Number(v);return Number.isFinite(v)?v:null}
function price(){const m=window.market||{};const cand=[m.price,document.getElementById('livePrice')?.textContent,document.getElementById('btcCurrentPrice')?.textContent,document.querySelector('[data-btc-price]')?.textContent];for(const x of cand){const v=n(String(x??'').replace(/[^0-9.-]/g,''));if(v&&v>1000)return v}return null}
function modules(){const keys=['BTCSafetyCore','BTCRegimeHedge','BTCAdaptiveLearning','BTCStrategyGovernance','BTCTerminalWallet','BTCRecoveryEngine','BTCStabilityGuard','BTCStartupHealth'];return keys.filter(k=>!window[k])}
function duplicateIds(){const seen=new Set(),d=[];document.querySelectorAll('[id]').forEach(x=>{if(seen.has(x.id)&&!d.includes(x.id))d.push(x.id);seen.add(x.id)});return d}
function setClosed(reasons){S.reasons=[...new Set(reasons)];S.failClosed=S.reasons.length>0;if(S.failClosed){window.BTC_DECISION_ALLOWED=false;window.BTC_HEALTH_FAIL_CLOSED=true;window.BTC_RELIABILITY_REASON=S.reasons.join(',')}else if(!window.BTC_BOOTSTRAP_ERROR){window.BTC_HEALTH_FAIL_CLOSED=false;window.BTC_RELIABILITY_REASON=''}document.documentElement.dataset.btcReliability=S.failClosed?'fail-closed':'healthy'}
function check(){S.checks++;S.lastCheck=Date.now();const reasons=[];const p=price();if(p!==null){if(S.lastPrice===null||Math.abs(p-S.lastPrice)>.000001){S.lastPrice=p;S.lastPriceAt=Date.now();S.staleSince=0}else if(!S.staleSince)S.staleSince=S.lastPriceAt||Date.now()}const grace=Date.now()-S.startedAt<30000;if(!grace&&(!S.lastPriceAt||Date.now()-S.lastPriceAt>Number(cfg().priceStaleMs||120000)))reasons.push('price-stale');const miss=modules();if(miss.length)reasons.push('critical-module:'+miss.join('|'));if(window.BTC_BOOTSTRAP_ERROR)reasons.push('bootstrap-error');const dup=duplicateIds();if(dup.length)reasons.push('duplicate-id:'+dup.slice(0,5).join('|'));setClosed(reasons);const out={version:V,at:new Date().toISOString(),price:S.lastPrice,priceAgeMs:S.lastPriceAt?Date.now()-S.lastPriceAt:null,failClosed:S.failClosed,reasons:[...S.reasons],checks:S.checks,recoveries:S.recoveries,duplicateIds:dup};window.BTC_RELIABILITY=out;document.dispatchEvent(new CustomEvent('btc-reliability',{detail:out}));return out}
function recover(){S.recoveries++;try{window.BTCStabilityCleanup?.check?.()}catch(e){};try{window.BTCV8223?.rehomeEngines?.()}catch(e){};try{window.BTCSafetyHealth?.check?.()}catch(e){};return check()}
let timer=null;function start(){if(timer)return;setTimeout(check,1500);timer=setInterval(()=>{const r=check();if(r.failClosed)recover()},30000)}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)recover()});window.addEventListener('online',recover);window.addEventListener('pageshow',recover);document.addEventListener('btc-bootstrap-ready',()=>setTimeout(recover,300));
window.BTCReliabilityCore={version:V,check,recover,status:()=>window.BTC_RELIABILITY||null};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();