/* BTC Hedge Assistant v8.23.9 - Reliability Core 1.2 / bounded DOM audit */
(()=>{'use strict';
if(window.__BTC_RELIABILITY_CORE__&&window.BTCReliabilityCore)return;window.__BTC_RELIABILITY_CORE__=true;
const V='8.23.9',S={startedAt:Date.now(),lastCheck:0,lastPrice:null,lastPriceAt:0,lastObservedAt:0,lastSourceStamp:null,failClosed:false,reasons:[],checks:0,recoveries:0,lastDomAudit:0,duplicateIds:[]};
const cfg=()=>window.BTC_APP_CONFIG?.safety||{};function n(v){v=Number(v);return Number.isFinite(v)?v:null}
function read(){const m=window.market||{},els=[document.getElementById('livePrice'),document.getElementById('btcCurrentPrice'),document.querySelector('[data-btc-price]')];const cand=[m.price,...els.map(e=>e?.textContent)];let p=null;for(const x of cand){const v=n(String(x??'').replace(/[^0-9.-]/g,''));if(v&&v>1000){p=v;break}}const stamp=m.updatedAt||m.timestamp||m.ts||m.lastUpdate||els.map(e=>e?.dataset?.updatedAt||e?.dataset?.timestamp).find(Boolean)||null;return{price:p,stamp}}
function modules(){const keys=['BTCSafetyCore','BTCRegimeHedge','BTCAdaptiveLearning','BTCStrategyGovernance','BTCTerminalWallet','BTCRecoveryEngine','BTCStabilityGuard','BTCStartupHealth'];return keys.filter(k=>!window[k])}
function duplicateIds(force=false){const now=Date.now();if(!force&&S.lastDomAudit&&now-S.lastDomAudit<120000)return S.duplicateIds;const seen=new Set(),d=[];document.querySelectorAll('[id]').forEach(x=>{if(seen.has(x.id)&&!d.includes(x.id))d.push(x.id);seen.add(x.id)});S.lastDomAudit=now;S.duplicateIds=d;return d}
function markReceipt(r){if(r.price===null)return;const now=Date.now();let fresh=false;if(r.stamp!==null&&String(r.stamp)!==String(S.lastSourceStamp)){S.lastSourceStamp=r.stamp;fresh=true}else if(S.lastPrice===null||Math.abs(r.price-S.lastPrice)>.000001)fresh=true;else if(document.visibilityState==='visible'&&navigator.onLine&&now-S.lastObservedAt>=25000)fresh=true;S.lastPrice=r.price;S.lastObservedAt=now;if(fresh)S.lastPriceAt=now}
function setClosed(reasons){S.reasons=[...new Set(reasons)];S.failClosed=S.reasons.length>0;if(S.failClosed){window.BTC_DECISION_ALLOWED=false;window.BTC_HEALTH_FAIL_CLOSED=true;window.BTC_RELIABILITY_REASON=S.reasons.join(',')}else if(!window.BTC_BOOTSTRAP_ERROR){window.BTC_HEALTH_FAIL_CLOSED=false;window.BTC_RELIABILITY_REASON=''}document.documentElement.dataset.btcReliability=S.failClosed?'fail-closed':'healthy'}
function check(forceDom=false){S.checks++;S.lastCheck=Date.now();const reasons=[],r=read();markReceipt(r);const grace=Date.now()-S.startedAt<30000;if(!grace&&(!S.lastPriceAt||Date.now()-S.lastPriceAt>Number(cfg().priceStaleMs||120000)))reasons.push('price-stale');const miss=modules();if(miss.length)reasons.push('critical-module:'+miss.join('|'));if(window.BTC_BOOTSTRAP_ERROR)reasons.push('bootstrap-error');const dup=duplicateIds(forceDom);if(dup.length)reasons.push('duplicate-id:'+dup.slice(0,5).join('|'));setClosed(reasons);const out={version:V,at:new Date().toISOString(),price:S.lastPrice,priceReceiptAgeMs:S.lastPriceAt?Date.now()-S.lastPriceAt:null,failClosed:S.failClosed,reasons:[...S.reasons],checks:S.checks,recoveries:S.recoveries,duplicateIds:dup,domAuditAgeMs:S.lastDomAudit?Date.now()-S.lastDomAudit:null};window.BTC_RELIABILITY=out;document.dispatchEvent(new CustomEvent('btc-reliability',{detail:out}));return out}
function receipt(price,stamp){const p=n(price);if(p&&p>1000){S.lastPrice=p;S.lastPriceAt=Date.now();S.lastObservedAt=S.lastPriceAt;if(stamp!==undefined)S.lastSourceStamp=stamp}return check(false)}
function recover(){S.recoveries++;try{window.BTCStabilityCleanup?.check?.()}catch(e){};try{window.BTCV8223?.rehomeEngines?.()}catch(e){};try{window.BTCSafetyHealth?.check?.()}catch(e){};return check(true)}
let timer=null;function start(){if(timer)return;setTimeout(()=>check(true),1500);timer=setInterval(()=>{if(document.hidden)return;const r=check(false);if(r.failClosed)recover()},30000)}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)recover()});window.addEventListener('online',recover);window.addEventListener('pageshow',recover);document.addEventListener('btc-bootstrap-ready',()=>setTimeout(recover,300));document.addEventListener('btc-price-received',e=>receipt(e.detail?.price,e.detail?.timestamp));
window.BTCReliabilityCore={version:V,check,recover,receipt,status:()=>window.BTC_RELIABILITY||null};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();