/* BTC Hedge Assistant v8.20.3 - Unified Research Health / daemon-aware stale governance gate */
(function(){'use strict';
const V='8.20.3',ID='btcResearchHealth';let DATA=null,LAB=null,HEART=null,LAST_OK=0,LAB_OK=0,ERR='',LAB_ERR='',HEART_ERR='';
const CFG=()=>window.BTC_APP_CONFIG?.safety||{};
function home(){return document.getElementById('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function ageOf(x){const t=Date.parse(x?.generatedAt||x?.enhancedAt||x?.at||'');return Number.isFinite(t)?Math.max(0,Date.now()-t):Infinity}
function classify(age,freshMin,stopMin){return age<=freshMin*60000?'LIVE':age<=stopMin*60000?'STALE':'STOPPED'}
function stamp(x){return Date.parse(x?.generatedAt||x?.enhancedAt||x?.at||'')||0}
function state(){const c=CFG(),researchAge=ageOf(DATA),labAge=ageOf(LAB),heartAge=ageOf(HEART),rf=Number(c.researchFreshMinutes)||45,rs=Number(c.researchStoppedMinutes)||120,lf=Number(c.labFreshMinutes)||300,ls=Number(c.labStoppedMinutes)||600,dh=Number(c.daemonHeartbeatMinutes)||35,researchStatus=classify(researchAge,rf,rs),labStatus=classify(labAge,lf,ls),researchFresh=researchStatus==='LIVE',labFresh=labStatus==='LIVE',daemonAlive=HEART?.event==='daemon'&&heartAge<=dh*60000,automationHealthy=daemonAlive||((HEART?.event==='schedule'||HEART?.event==='watchdog')&&heartAge<=dh*60000);return{version:V,ready:!!DATA,research:{status:researchStatus,fresh:researchFresh,ageMs:researchAge,generatedAt:DATA?.generatedAt||null,engineVersion:DATA?.engineVersion||null,error:ERR,lastOk:LAST_OK},lab:{status:labStatus,fresh:labFresh,ageMs:labAge,generatedAt:LAB?.generatedAt||null,engineVersion:LAB?.engineVersion||null,error:LAB_ERR,lastOk:LAB_OK},heartbeat:{ageMs:heartAge,at:HEART?.at||null,event:HEART?.event||null,trigger:HEART?.trigger||null,workflow:HEART?.workflow||null,runId:HEART?.runId||null,loop:HEART?.loop||null,cadenceMinutes:HEART?.cadenceMinutes||null,error:HEART_ERR,daemonAlive,automationHealthy},fresh:researchFresh,stale:researchStatus==='STALE',stopped:researchStatus==='STOPPED',promotionAllowed:!!DATA&&researchFresh,serverDecisionUsable:!!DATA&&researchFresh,labPromotionAllowed:!!LAB&&labFresh,automationHealthy}}
function publish(){const s=state();window.BTC_RESEARCH_HEALTH=s;window.BTC_RESEARCH_PROMOTION_ALLOWED=s.promotionAllowed;window.BTC_SERVER_RESEARCH_USABLE=s.serverDecisionUsable;window.BTC_LAB_PROMOTION_ALLOWED=s.labPromotionAllowed;window.BTC_RESEARCH_AUTOMATION_HEALTHY=s.automationHealthy;document.dispatchEvent(new CustomEvent('btc-research-health',{detail:s}));return s}
async function getJson(u){const r=await fetch(u,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function fetchFreshest(path,key){const ts=Date.now(),urls=['./'+path+'?'+key+'='+ts,'/btc/'+path+'?'+key+'='+ts,'https://raw.githubusercontent.com/ztman000-bot/btc/main/'+path+'?'+key+'='+ts],es=[],ok=[];await Promise.all(urls.map(async u=>{try{ok.push(await getJson(u))}catch(e){es.push(String(e?.message||e))}}));if(!ok.length)throw new Error(es.join(' / '));ok.sort((a,b)=>stamp(b)-stamp(a));return ok[0]}
async function refresh(){try{DATA=await fetchFreshest('data/research/latest.json','health');LAST_OK=Date.now();ERR=''}catch(e){ERR=String(e?.message||e)}try{LAB=await fetchFreshest('data/research/lab-latest.json','labhealth');LAB_OK=Date.now();LAB_ERR=''}catch(e){LAB_ERR=String(e?.message||e)}try{HEART=await fetchFreshest('data/research/research-heartbeat.json','heartbeat');HEART_ERR=''}catch(e){HEART_ERR=String(e?.message||e)}render();return state()}
function ensure(){let c=document.getElementById(ID);if(c)return c;c=document.createElement('div');c.id=ID;c.className='card';c.style.cssText='display:block!important;width:100%!important;max-width:100%!important;margin:0 0 10px!important';const p=home();if(p){const a=document.getElementById('btcStartupHealth');if(a&&a.parentNode===p)a.insertAdjacentElement('afterend',c);else p.insertBefore(c,p.firstChild)}return c}
function ago(ms){if(!Number.isFinite(ms))return'알 수 없음';const m=ms/60000;if(m<1)return'방금';if(m<60)return Math.round(m)+'분 전';return(m/60).toFixed(1)+'시간 전'}
function tone(status){return status==='LIVE'?'okbox':status==='STALE'?'warnbox':'notice'}
function render(){const c=ensure();if(!c)return;const s=publish(),r=s.research,l=s.lab,h=s.heartbeat,headline=r.status==='LIVE'?'24H Research 데이터 정상':r.status==='STALE'?'24H Research 지연 · 승격 동결':'24H Research 중단 · 서버 근거 사용 금지',auto=h.daemonAlive?'DAEMON LIVE':h.automationHealthy?'FALLBACK LIVE':'AUTOMATION DOWN',autoCls=h.automationHealthy?'okbox':'notice',trigger=h.workflow?((h.workflow||'')+' / '+(h.event||'unknown')):'heartbeat 대기';c.innerHTML='<div class="row"><div><b>🔬 Research Health</b><div class="small">24H Daemon · Shadow · Forward/OOS · Monte Carlo · Strategy Lab</div></div><span class="badge">'+r.status+'</span></div><div class="'+autoCls+'"><b>'+auto+'</b><br>최근 자동실행 '+ago(h.ageMs)+(h.loop?' · daemon loop '+h.loop:'')+'</div><div class="'+tone(r.status)+'" style="margin-top:7px"><b>'+headline+'</b><br>24H Research 마지막 갱신 '+ago(r.ageMs)+' · Engine '+(r.engineVersion||'--')+'</div><div class="'+tone(l.status)+'" style="margin-top:7px"><b>Strategy Lab '+l.status+'</b> · 마지막 계산 '+ago(l.ageMs)+'</div><div class="tiny" style="margin-top:7px">최근 Research 실행: '+trigger+' · '+ago(h.ageMs)+(h.runId?' · run '+h.runId:'')+'</div><div class="tiny" style="margin-top:6px">기본 운용은 Self-Chaining Research Daemon이 15분 주기로 지속합니다. GitHub cron은 보조 경로입니다. 24H Research 45분 초과 STALE / 2시간 초과 STOPPED, Strategy Lab 5시간 초과 STALE / 10시간 초과 STOPPED. 오래된 데이터는 승격·서버 MC 실전근거로 사용하지 않습니다. Central Safety/10K Guard는 계속 작동합니다.'+(ERR?' · Research loader: '+ERR:'')+(LAB_ERR?' · Lab loader: '+LAB_ERR:'')+(HEART_ERR?' · heartbeat: '+HEART_ERR:'')+'</div>'}
function boot(){ensure();refresh();[2500,7000,15000].forEach(ms=>setTimeout(refresh,ms));setInterval(refresh,60000);setInterval(render,15000)}
window.BTCResearchHealth={version:V,status:state,refresh,render,data:()=>DATA,labData:()=>LAB,heartbeat:()=>HEART};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();