/* BTC Hedge Assistant v8.22.2 - 24H Research & Shadow dashboard */
(()=>{'use strict';
if(window.__BTC_RESEARCH_SHADOW_SINGLETON&&window.BTCResearchShadow)return;window.__BTC_RESEARCH_SHADOW_SINGLETON=true;
const V='2.2',$=id=>document.getElementById(id);let LAST=null,ERR='';
function host(){return $('v8222ResearchShadowSlot')||$('v8222ResearchAuxSlot')||null}
function ensure(){const p=host();if(!p)return null;let c=$('researchShadowCard');if(!c){c=document.createElement('div');c.id='researchShadowCard';c.className='card';c.dataset.role='research-shadow-dashboard'}if(c.parentElement!==p)p.appendChild(c);c.classList.remove('v853Page','v852Page','v851Page','tabPane','activePane');c.style.cssText='width:100%;max-width:100%;min-width:0;margin:0 0 10px';return c}
const money=x=>Number.isFinite(Number(x))?'$'+Math.round(Number(x)).toLocaleString():'--',pct=x=>Number.isFinite(Number(x))?(Number(x)*100).toFixed(1)+'%':'--';
function age(ts){if(!ts)return'첫 실행 대기';const m=(Date.now()-new Date(ts).getTime())/60000;if(m<2)return'방금 갱신';if(m<120)return Math.round(m)+'분 전';return(m/60).toFixed(1)+'시간 전'}
function actionLabel(id){return({HOLD:'관망',SHORT_0.025:'숏 0.025 축소',SHORT_0.050:'숏 0.050 축소',LONG_0.025:'롱 0.025 축소',LONG_0.050:'롱 0.050 축소',EXIT_ALL:'양 포지션 전량종료'})[id]||id||'--'}
async function getJson(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function refresh(){const ts=Date.now(),urls=['./data/research/latest.json?t='+ts,'/btc/data/research/latest.json?t='+ts,'https://raw.githubusercontent.com/ztman000-bot/btc/main/data/research/latest.json?t='+ts],ok=[],es=[];await Promise.all(urls.map(async u=>{try{ok.push(await getJson(u))}catch(e){es.push(String(e?.message||e))}}));if(ok.length){ok.sort((a,b)=>(Date.parse(b.generatedAt||'')||0)-(Date.parse(a.generatedAt||'')||0));LAST=ok[0];ERR=''}else ERR=es.join(' / ');render()}
function render(){const c=ensure();if(!c)return;const d=LAST;if(!d||d.status==='waiting_first_run'){c.innerHTML=`<div class="row"><div><b>🛰️ 24H Research & Shadow</b><div class="small">서버 연구 · 실거래 없음</div></div><span class="badge">APP v${window.BTC_APP_VERSION||'--'}</span></div><div class="warnbox"><b>${ERR?'서버 데이터 연결 확인 중':'첫 서버 연구 실행 대기'}</b><br>${ERR||'Shadow Trading·Forward Test·Monte Carlo 결과가 자동 표시됩니다.'}</div>`;return}if(d.status==='error'){c.innerHTML=`<div class="row"><b>🛰️ 24H Research & Shadow</b><span class="badge">ENGINE ${V}</span></div><div class="notice"><b>서버 연구 오류</b><br>${d.error||'원인 미상'}</div>`;return}const t=d.terminalWallet||{},sh=d.shadow||{},mc=d.monteCarlo||{},op=d.optimizer||{},ms=d.marketStructure||{},exe=t.executable||{},best=t.modelBest||{},rh=window.BTCResearchHealth?.status?.()||window.BTC_RESEARCH_HEALTH||null,fresh=rh?rh.fresh:(d.generatedAt&&(Date.now()-new Date(d.generatedAt).getTime())<45*60000),auto=rh?.automationHealthy,stopped=rh?.stopped,tone=fresh?'okbox':stopped?'notice':'warnbox',status=fresh?(auto?'🟢 Research Daemon 정상':'🟡 데이터 최신 · 자동실행 점검'):(stopped?'🔴 Research 중단':'🟠 Research 지연');c.innerHTML=`<div class="row"><div><b>🛰️ 24H Research & Shadow</b><div class="small">연구소 전용 상태판 · 다른 화면에는 표시하지 않습니다.</div></div><span class="badge">APP v${window.BTC_APP_VERSION||'--'} · ENGINE ${V}</span></div><div class="${tone}" style="margin-top:8px"><b>${status}</b> · ${age(d.generatedAt)}<br>최종 실행판정: <b>${actionLabel(exe.id)}</b> · 모델 1위 ${actionLabel(best.id)}</div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">Shadow 표본</div><b>${sh.samples??0}회</b><div class="tiny">Forward 평가 ${sh.directionalEvaluations??0}회</div></div><div class="kpi"><div class="small">Forward 방향승률</div><b>${sh.directionalWinRate==null?'대기':pct(sh.directionalWinRate)}</b></div><div class="kpi"><div class="small">서버 Champion</div><b>${op.best?.name||'BASE'}</b><div class="tiny">Governance ${op.approved?'승인':'미승인/보수화'}</div></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">기대 최종 Wallet</div><b>${money(exe.expectedWallet)}</b></div><div class="kpi"><div class="small">Recovery 확률</div><b>${pct(exe.recoveryProbability)}</b></div><div class="kpi"><div class="small">최악 MC Wallet</div><b>${money(exe.worst)}</b></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">Monte Carlo</div><b>${mc.paths||0}경로</b><div class="tiny">${mc.steps||0} steps</div></div><div class="kpi"><div class="small">시장 과열</div><b>${ms.heat??'--'}/100</b><div class="tiny">Funding ${pct(ms.funding)}</div></div><div class="kpi"><div class="small">현재 순청산가치</div><b>${money(t.currentNetClose)}</b></div></div>`}
function heal(){try{if(LAST)render()}catch(e){ERR=String(e?.message||e)}}
function boot(){refresh();window.__BTC_RESEARCH_SHADOW_REFRESH_TIMER=setInterval(refresh,60000);window.__BTC_RESEARCH_SHADOW_HEAL_TIMER=setInterval(heal,15000);document.addEventListener('btc-research-health',()=>setTimeout(render,20));document.addEventListener('btc-strategy-lab-rendered',()=>setTimeout(render,20))}
window.BTCResearchShadow={version:V,refresh,render,heal,status:()=>LAST};window.dispatchEvent(new CustomEvent('btc-research-shadow-ready',{detail:{version:V}}));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();