/* BTC Hedge Assistant v8.18.0 - 24H Research & Shadow dashboard */
(()=>{'use strict';const V='8.18.0',$=id=>document.getElementById(id);let LAST=null,ERR='';
function pane(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function ensure(){let c=$('researchShadowCard');if(!c){c=document.createElement('div');c.id='researchShadowCard';c.className='card'}const p=pane();if(p&&c.parentElement!==p){const a=$('terminalWalletCard')||$('executionExitCard');if(a&&a.parentElement===p)a.insertAdjacentElement('afterend',c);else p.appendChild(c)}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.cssText+=';display:block;width:100%;max-width:100%;min-width:0';return c}
const money=x=>Number.isFinite(Number(x))?'$'+Math.round(Number(x)).toLocaleString():'--',pct=x=>Number.isFinite(Number(x))?(Number(x)*100).toFixed(1)+'%':'--';
function age(ts){if(!ts)return'첫 실행 대기';const m=(Date.now()-new Date(ts).getTime())/60000;if(m<2)return'방금 갱신';if(m<120)return Math.round(m)+'분 전';return (m/60).toFixed(1)+'시간 전'}
function actionLabel(id){return({HOLD:'관망',SHORT_0.025:'숏 0.025 축소',SHORT_0.050:'숏 0.050 축소',LONG_0.025:'롱 0.025 축소',LONG_0.050:'롱 0.050 축소',EXIT_ALL:'양 포지션 전량종료'})[id]||id||'--'}
async function refresh(){try{const r=await fetch('./data/research/latest.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);LAST=await r.json();ERR='';render()}catch(e){ERR=String(e?.message||e);render()}}
function render(){const c=ensure();if(!c)return;const d=LAST;if(!d||d.status==='waiting_first_run'){c.innerHTML=`<div class="row"><div><b>🛰️ 24H Research & Shadow</b><div class="small">GitHub Actions 서버 연구 · 실거래 없음</div></div><span class="badge">v${V}</span></div><div class="warnbox"><b>첫 서버 연구 실행 대기</b><br>워크플로가 실행되면 Shadow Trading·Forward Test·Monte Carlo 결과가 자동 표시됩니다.${ERR?'<br>'+ERR:''}</div>`;return}if(d.status==='error'){c.innerHTML=`<div class="row"><b>🛰️ 24H Research & Shadow</b><span class="badge">v${V}</span></div><div class="notice"><b>서버 연구 오류</b><br>${d.error||'원인 미상'}</div>`;return}const t=d.terminalWallet||{},sh=d.shadow||{},mc=d.monteCarlo||{},op=d.optimizer||{},ms=d.marketStructure||{},exe=t.executable||{},best=t.modelBest||{},fresh=d.generatedAt&&(Date.now()-new Date(d.generatedAt).getTime())<45*60000,tone=fresh?'okbox':'warnbox';c.innerHTML=`<div class="row"><div><b>🛰️ 24H Research & Shadow</b><div class="small">앱을 꺼도 15분 주기로 연구 · 주문/계좌키 없음</div></div><span class="badge">v${V}</span></div><div class="${tone}"><b>${fresh?'✅ 서버 연구 정상':'🟡 서버 데이터 지연'}</b> · ${age(d.generatedAt)}<br>최종 실행판정: <b>${actionLabel(exe.id)}</b> · 모델 1위 ${actionLabel(best.id)}</div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">Shadow 표본</div><b>${sh.samples??0}회</b><div class="tiny">Forward 평가 ${sh.directionalEvaluations??0}회</div></div><div class="kpi"><div class="small">Forward 방향승률</div><b>${sh.directionalWinRate==null?'대기':pct(sh.directionalWinRate)}</b></div><div class="kpi"><div class="small">서버 Champion</div><b>${op.best?.name||'BASE'}</b><div class="tiny">Governance ${op.approved?'승인':'미승인/보수화'}</div></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">기대 최종 Wallet</div><b>${money(exe.expectedWallet)}</b></div><div class="kpi"><div class="small">Recovery 확률</div><b>${pct(exe.recoveryProbability)}</b></div><div class="kpi"><div class="small">최악 MC Wallet</div><b>${money(exe.worst)}</b></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">Monte Carlo</div><b>${mc.paths||0}경로</b><div class="tiny">${mc.steps||0} steps</div></div><div class="kpi"><div class="small">시장 과열</div><b>${ms.heat??'--'}/100</b><div class="tiny">Funding ${pct(ms.funding)}</div></div><div class="kpi"><div class="small">현재 순청산가치</div><b>${money(t.currentNetClose)}</b></div></div><details style="margin-top:9px"><summary class="small"><b>서버 연구 상세</b></summary><div class="tiny" style="line-height:1.7;margin-top:7px">4H 장세점수 ${d.market?.regimeScore??'--'}/100 · ATR ${pct(d.market?.atr4hPct)} · OOS 후보 ${op.tested??0}개 / ${op.folds??0}구간 · MC 종가 P10 ${money(mc.terminalPriceP10)} / 중앙 ${money(mc.terminalPriceMedian)} / P90 ${money(mc.terminalPriceP90)}.<br>서버 연구는 별도 research config 기준 포지션으로 Shadow만 수행하며 실거래 주문은 전혀 전송하지 않습니다.</div></details>`}
function boot(){render();refresh();setInterval(refresh,60000)}window.BTCResearchShadow={version:V,refresh,status:()=>LAST};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();