/* BTC Hedge Assistant - Smart 3~5 Minute Session Mode 2.0 */
(()=>{
'use strict';
if(window.__BTC_SMART_SESSION_SINGLETON&&window.BTCSmartSession)return;window.__BTC_SMART_SESSION_SINGLETON=true;
const VERSION='2.0',AUTO_KEY='btc_auto_top10_v872',VISIT_KEY='btc_smart_visit_v882',OPP_KEY='btc_opp_enrich_v880',STALE_MS=30*60*1000,SESSION_MAX=5*60*1000,$=id=>document.getElementById(id),n=v=>Number.isFinite(Number(v))?Number(v):null,esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const load=(k,f=null)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
const auto=()=>load(AUTO_KEY,null),opp=()=>load(OPP_KEY,{}),startedAt=Date.now();
let previousVisit=load(VISIT_KEY,null),startAutoTs=Number(auto()?.ts||0),refreshRequested=false,refreshFinished=false;
function ranked(rows,m='all'){return [...(rows||[])].filter(r=>m==='all'||r.type===m).sort((a,b)=>(n(b.score)||0)-(n(a.score)||0))}
function rankMap(rows,m='all'){const map={};ranked(rows,m).forEach((r,i)=>{map[`${r.type}:${r.symbol}`]=i+1});return map}
function snapshot(){const A=auto();if(!A?.rows?.length)return null;const O=opp();const rows=A.rows.map(r=>{const k=`${r.type}:${r.symbol}`,x=O[k];return{symbol:r.symbol,type:r.type,name:r.name||r.symbol,score:n(r.score),direction:r.direction||'WAIT',long:n(r.long),short:n(r.short),wait:n(r.wait),trigger:x?.trigger?.state||'',triggerOk:!!x?.trigger?.ok,grade:x?.grade?.grade||'',gradeScore:n(x?.grade?.score),rr:n(x?.rr)}});return{savedAt:Date.now(),autoTs:Number(A.ts||0),version:VERSION,rows}}
function saveVisit(){const s=snapshot();if(s)save(VISIT_KEY,s)}
function compare(){
  const cur=snapshot(),prev=previousVisit;if(!cur||!prev?.rows?.length)return{items:[],note:'이 방문부터 변화 비교 기준을 저장합니다.'};
  const cm=rankMap(cur.rows),pm=rankMap(prev.rows),pRows=new Map(prev.rows.map(r=>[`${r.type}:${r.symbol}`,r])),items=[];
  for(const r of ranked(cur.rows).slice(0,15)){
    const k=`${r.type}:${r.symbol}`,cr=cm[k],pr=pm[k],old=pRows.get(k),sd=old&&n(old.score)!=null&&n(r.score)!=null?Math.round((r.score-old.score)*10)/10:null;
    if(pr==null||pr>10){if(cr<=10)items.push({w:50+Math.max(0,10-cr),text:`${r.name} NEW TOP10 · 현재 #${cr} · ${r.direction}`});continue}
    if(old&&old.direction!==r.direction&&r.direction!=='WAIT')items.push({w:45,text:`${r.name} ${old.direction} → ${r.direction} 전환`});
    if(old&&!old.triggerOk&&r.triggerOk)items.push({w:60,text:`${r.name} 🎯 진입 가능 전환${r.rr!=null?` · R:R ${r.rr.toFixed(2)}`:''}`});
    if(cr<pr&&pr-cr>=2)items.push({w:30+(pr-cr),text:`${r.name} #${pr} → #${cr} ▲${pr-cr}`});
    if(sd!=null&&sd>=3)items.push({w:25+sd/2,text:`${r.name} 적합도 +${sd.toFixed(1)}점`});
  }
  const cKeys=new Set(cur.rows.map(r=>`${r.type}:${r.symbol}`));for(const r of ranked(prev.rows).slice(0,10)){const k=`${r.type}:${r.symbol}`;if(!cKeys.has(k))continue;const cr=cm[k],pr=pm[k];if(pr<=10&&cr>10)items.push({w:18,text:`${r.name} TOP10 이탈 · #${pr} → #${cr}`})}
  const uniq=[],seen=new Set();for(const x of items.sort((a,b)=>b.w-a.w)){if(seen.has(x.text))continue;seen.add(x.text);uniq.push(x);if(uniq.length>=5)break}return{items:uniq,note:uniq.length?'지난 방문 이후 의미 있는 변화':'지난 방문 이후 큰 변화 없음'}
}
function ageText(ts){if(!ts)return'분석 기록 없음';const m=Math.max(0,Math.round((Date.now()-ts)/60000));return m<1?'방금 전':`${m}분 전`}
function status(){const A=auto(),age=A?.ts?Date.now()-A.ts:Infinity;if(refreshFinished)return{cls:'ssGood',main:'최신 분석 반영 완료',sub:`AUTO ${ageText(A?.ts)} · TOP10/기회레이더 재계산 완료`};if(refreshRequested)return{cls:'ssRun',main:'60종목 자동분석 진행 중',sub:'완료되면 TOP10과 기회레이더가 자동 갱신됩니다.'};if(age<=STALE_MS)return{cls:'ssGood',main:'캐시가 충분히 최신입니다',sub:`AUTO ${ageText(A?.ts)} · 30분 이내라 전체 재분석을 생략했습니다.`};return{cls:'ssWarn',main:'시장 재분석 준비',sub:`마지막 AUTO ${ageText(A?.ts)} · 곧 60종목 자동분석을 시작합니다.`}}
function css(){if($('smartSessionStyle'))return;const s=document.createElement('style');s.id='smartSessionStyle';s.textContent='.ssCard{margin:10px 0;padding:11px;border:1px solid #34516f;border-radius:14px;background:linear-gradient(180deg,#102033,#0b1622)}.ssHead{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.ssTitle{font-size:14px;font-weight:900}.ssSmall{font-size:10px;color:#91a1b3;line-height:1.5}.ssState{font-size:11px;font-weight:850;margin-top:6px}.ssGood{color:#20d792}.ssWarn{color:#ffbf47}.ssRun{color:#67a7ff}.ssChanges{display:grid;gap:5px;margin-top:8px}.ssChange{padding:7px 8px;border:1px solid #293b4e;border-radius:9px;background:#0a141e;font-size:10px;color:#c6d2df}.ssBtns{display:flex;gap:6px;margin-top:8px}.ssBtns button{padding:7px 9px;font-size:10px}';document.head.appendChild(s)}
function ensureCards(){css();const home=$('v850HomePane');if(home&&!$('smartSessionHome')){const c=document.createElement('section');c.id='smartSessionHome';c.className='ssCard';const q=$('v853HomeQuick');q?home.insertBefore(c,q):home.appendChild(c)}const radar=$('top10Radar');if(radar&&!$('smartSessionRadar')){const c=document.createElement('section');c.id='smartSessionRadar';c.className='ssCard';const hero=radar.querySelector('.t10Hero');hero?hero.insertAdjacentElement('afterend',c):radar.prepend(c)}}
function paint(){ensureCards();const st=status(),cmp=compare(),elapsed=Math.round((Date.now()-startedAt)/1000),html=`<div class="ssHead"><div><div class="ssTitle">⚡ 스마트 세션 모드 <span class="ssSmall">3~5분 최적화</span></div><div class="ssState ${st.cls}">${esc(st.main)}</div><div class="ssSmall">${esc(st.sub)}</div></div><span class="ssSmall">세션 ${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')}</span></div><div class="ssChanges"><div class="ssSmall"><b>${esc(cmp.note)}</b></div>${cmp.items.length?cmp.items.map(x=>`<div class="ssChange">${esc(x.text)}</div>`).join(''):'<div class="ssChange">기준 데이터가 쌓이면 신규 TOP10·순위상승·점수변화·진입가능 전환을 요약합니다.</div>'}</div><div class="ssBtns"><button data-ss-refresh>지금 60종목 재분석</button><button data-ss-top>TOP10 보기</button></div>`;for(const id of ['smartSessionHome','smartSessionRadar']){const el=$(id);if(!el)continue;el.innerHTML=html;el.querySelector('[data-ss-refresh]')?.addEventListener('click',()=>requestRefresh(true));el.querySelector('[data-ss-top]')?.addEventListener('click',()=>window.BTCAutoTop10?.open?.())}}
async function waitReady(ms=12000){const end=Date.now()+ms;while(Date.now()<end){if(window.BTCAutoTop10?.run)return true;await new Promise(r=>setTimeout(r,300))}return false}
async function requestRefresh(force=false){if(refreshRequested&&!force)return;const A=auto(),stale=!A?.ts||Date.now()-A.ts>STALE_MS;if(!force&&!stale){paint();return}if(!await waitReady())return;refreshRequested=true;refreshFinished=false;startAutoTs=Number(A?.ts||0);paint();try{window.BTCAutoTop10.run()}catch(e){refreshRequested=false;paint()}}
function detectAutoUpdate(){const ts=Number(auto()?.ts||0);if(refreshRequested&&ts>startAutoTs){refreshRequested=false;refreshFinished=true;try{window.BTCTop10History?.capture?.()}catch(e){}setTimeout(()=>{try{window.BTCOpportunityV2?.refresh?.(true)}catch(e){}},400);setTimeout(paint,1200);setTimeout(paint,5000)}}
function boot(){css();ensureCards();paint();setTimeout(()=>requestRefresh(false),3500);window.__BTC_SMART_SESSION_TIMER=setInterval(()=>{detectAutoUpdate();if(Date.now()-startedAt<SESSION_MAX+60000)paint()},2000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){paint();const A=auto();if(!A?.ts||Date.now()-A.ts>STALE_MS)setTimeout(()=>requestRefresh(false),1500)}else if(Date.now()-startedAt>15000)saveVisit()});window.addEventListener('pagehide',saveVisit);setTimeout(saveVisit,4*60*1000);if(!window.__BTC_SMART_SESSION_OBSERVER){window.__BTC_SMART_SESSION_OBSERVER=new MutationObserver(()=>ensureCards());window.__BTC_SMART_SESSION_OBSERVER.observe(document.body,{childList:true,subtree:true})}}
window.BTCSmartSession={version:VERSION,refresh:()=>requestRefresh(true),saveVisit,compare,status};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1600),{once:true});else setTimeout(boot,1600);
})();