/* BTC Hedge Assistant - Strategy Research Lab v2.6 server-backed */
(()=>{'use strict';
const VERSION='2.6',PAGE='strategyLab',$=id=>document.getElementById(id),fmt=(v,d=1)=>v==null||!Number.isFinite(Number(v))?'--':Number(v).toFixed(d),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let SERVER=null,ERR='',FETCH_STATE='idle',LAST_CHECK=0,LAST_RESULT='',BUSY=false;
function style(){if($('v2LabStyle'))return;const s=document.createElement('style');s.id='v2LabStyle';s.textContent=`#strategyLab{max-width:980px;margin:0 auto;padding:2px 0 110px}.labHero{background:linear-gradient(180deg,#14243a,#0e1825);border:1px solid #35517a;border-radius:18px;padding:15px;margin-bottom:10px}.labTitle{font-size:23px;font-weight:900}.labSub{font-size:11px;color:#9aa6b2;line-height:1.55;margin-top:5px}.labGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.labCard{background:linear-gradient(180deg,#121b27,#0e1620);border:1px solid #27323f;border-radius:15px;padding:11px}.labCard.wide{grid-column:1/-1}.labMetric{font-size:23px;font-weight:900}.labTiny{font-size:10px;color:#91a0b0;line-height:1.45}.labTable{width:100%;border-collapse:collapse;font-size:10px;min-width:620px}.labTable th,.labTable td{padding:7px;border-bottom:1px solid #223040;text-align:right}.labTable th:first-child,.labTable td:first-child{text-align:left}.labScroll{overflow-x:auto}.labBadge{display:inline-block;padding:4px 7px;border:1px solid #3a4e66;border-radius:999px;font-size:10px}.labPromote{border-color:#285c48;background:#10271f}.labHold{border-color:#6d5626;background:#2a2111}.labList{display:grid;gap:6px;margin-top:7px}.labRow{display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid #223040;font-size:11px}.labBtn{width:100%;margin-top:8px}.labBtn:disabled{opacity:.72}.labRefreshStatus{margin-top:8px;padding:9px 10px;border-radius:10px;border:1px solid #334155;background:#0b141f;font-size:11px;line-height:1.55}.labRefreshStatus.loading{border-color:#35517a;background:#102035}.labRefreshStatus.ok{border-color:#285c48;background:#10271f;color:#baf2d8}.labRefreshStatus.same{border-color:#6d5626;background:#2a2111;color:#ffd486}.labRefreshStatus.bad{border-color:#713e47;background:#341a1f;color:#ffabb6}.labSectionTitle{font-size:15px;font-weight:900;margin:14px 2px 8px}@media(max-width:620px){.labGrid{grid-template-columns:1fr}.labCard.wide{grid-column:auto}}`;document.head.appendChild(s)}
function ensurePage(){style();const main=document.querySelector('main');if(!main)return null;let p=$(PAGE);if(!p){p=document.createElement('section');p.id=PAGE;main.appendChild(p)}if(p.parentElement!==main)main.appendChild(p);p.classList.add('v8222Page');p.classList.remove('v852Page','v851Page','tabPane','activePane');return p}
function localFallback(){let a=[];try{a=window.BTCLearning?.records?.()||JSON.parse(localStorage.getItem('v832learning')||'[]')}catch(e){}const s=a.filter(r=>r?.kind==='scanner_signal'&&r?.outcomes?.['4h']?.hit!=null),w=s.filter(r=>r.outcomes['4h'].hit).length,r=s.map(x=>Number(x.outcomes['4h'].directionalPct)||0);return{n:s.length,win:s.length?w/s.length*100:null,avg:r.length?r.reduce((x,y)=>x+y,0)/r.length:null}}
function health(){const h=window.BTCResearchHealth?.status?.()||window.BTC_RESEARCH_HEALTH;const ms=SERVER?.generatedAt?Date.now()-Date.parse(SERVER.generatedAt):Infinity;const st=h?.lab?.status||(ms<=5*3600e3?'LIVE':ms<=10*3600e3?'STALE':'STOPPED');return{status:st,fresh:st==='LIVE',ageMs:ms}}
function promotion(st){const h=health();if(!h.fresh)return{label:'승격 동결',why:'Strategy Lab 데이터가 오래되어 후보 승격을 중지함',pick:null};const cur=st?.[0];if(!cur||cur.n<20)return{label:'데이터 축적 중',why:`서버 평가표본 ${cur?.n||0}건 · 최소 20건 필요`,pick:null};const viable=st.slice(1).filter(x=>x.n>=20&&x.win!=null&&cur.win!=null&&x.win>=cur.win+5&&x.avg!=null&&cur.avg!=null&&x.avg>=cur.avg&&x.mdd>=cur.mdd);if(!viable.length)return{label:'현재 전략 유지',why:'후보가 표본·적중률 +5%p·평균수익·MDD 조건을 동시에 통과하지 못함',pick:null};viable.sort((a,b)=>(b.win-a.win)+(b.avg-a.avg)*2+(b.mdd-a.mdd)*.2);return{label:'승격 후보',why:`${viable[0].name}이 현재 전략보다 우세`,pick:viable[0]}}
function age(ts){if(!ts)return'--';const m=Math.max(0,(Date.now()-new Date(ts).getTime())/60000);return m<60?`${Math.round(m)}분 전`:`${(m/60).toFixed(1)}시간 전`}
function badge(st){return st==='LIVE'?'SERVER LIVE':st==='STALE'?'SERVER STALE':'SERVER STOPPED'}
function clock(ts){if(!ts)return'--';try{return new Date(ts).toLocaleString('ko-KR',{hour12:false})}catch(e){return'--'}}
function snapshotKey(d){if(!d)return'';return JSON.stringify({generatedAt:d.generatedAt||'',live:d.live||{},strategies:d.strategies||[],failures:d.failures||[],regimes:d.regimes||{}})}
function statusMarkup(){if(FETCH_STATE==='loading')return ['loading','⏳ <b>서버 결과 확인 중...</b><br>GitHub Pages와 원본 서버를 동시에 확인하고 있습니다.'];if(FETCH_STATE==='success')return ['ok',`✅ <b>최신 서버 결과 불러오기 완료</b><br>${esc(LAST_RESULT)} · 마지막 확인 ${clock(LAST_CHECK)}`];if(FETCH_STATE==='same')return ['same',`✅ <b>서버 연결 정상 · 변경 없음</b><br>${esc(LAST_RESULT)} · 마지막 확인 ${clock(LAST_CHECK)}`];if(FETCH_STATE==='error')return ['bad',`❌ <b>서버 연결 실패</b><br>${esc(ERR||'서버 연구 파일을 확인하지 못했습니다.')} · 마지막 확인 ${clock(LAST_CHECK)}`];return ['',`버튼을 누르면 서버 연결 여부와 새 데이터 반영 여부를 바로 표시합니다.`]}
function refreshStatusHtml(){const [c,h]=statusMarkup();return `<div class="labRefreshStatus ${c}" id="labRefreshStatus">${h}</div>`}
function paintRefresh(){const b=$('labRefreshBtn'),s=$('labRefreshStatus'),[c,h]=statusMarkup();if(b){b.disabled=FETCH_STATE==='loading';b.textContent=FETCH_STATE==='loading'?'⏳ 서버 결과 확인 중...':'최신 서버 결과 다시 불러오기'}if(s){s.className='labRefreshStatus '+c;s.innerHTML=h}}
function auxSlots(){return `<div class="labSectionTitle">연구 엔진 상태</div><div id="v8222ResearchAuxSlot"><div id="v8222ResearchHealthSlot"></div><div id="v8222ResearchShadowSlot"></div><div id="v8222RecoverySlot"></div></div>`}
function replacePage(p,html){const keep=$('v8223EngineHost');if(keep&&keep.parentElement===p)keep.remove();p.innerHTML=html;if(keep){const aux=$('v8222ResearchAuxSlot');if(aux&&aux.parentElement===p)p.insertBefore(keep,aux);else p.appendChild(keep)}}
function afterRender(){document.dispatchEvent(new CustomEvent('btc-strategy-lab-rendered',{detail:{version:VERSION}}));setTimeout(()=>{window.BTCV8223?.rehomeEngines?.();window.BTCResearchHealth?.render?.();window.BTCResearchShadow?.render?.();window.BTCRecoveryV2?.render?.();paintRefresh()},20)}
function render(){const p=ensurePage();if(!p)return;if(!SERVER){const l=localFallback();replacePage(p,`<div class="labHero"><div class="labTitle">전략 연구소 V2</div><div class="labSub">기존 전략 비교와 서버 연구엔진을 한 페이지에서 확인합니다.</div></div><div class="labGrid"><div class="labCard"><div class="labTiny">로컬 평가</div><div class="labMetric">${l.n}건</div><div class="labTiny">${l.win==null?'평가 대기':`적중 ${fmt(l.win)}% · 평균 ${fmt(l.avg,2)}%`}</div></div><div class="labCard labHold"><div class="labTiny">서버 상태</div><div class="labMetric">${ERR?'연결 점검':'불러오는 중'}</div><div class="labTiny">${esc(ERR||'서버 연구 파일 확인 중')}</div></div></div>${auxSlots()}`);afterRender();return}
const d=SERVER,st=Array.isArray(d.strategies)?d.strategies:[],h=health(),pr=promotion(st),live=d.live||{},regs=d.regimes||{},fails=Array.isArray(d.failures)?d.failures:[];const regRows=Object.entries(regs).sort((a,b)=>b[1].n-a[1].n).map(([k,x])=>`<div class="labRow"><span>${esc(k)}</span><b>${x.n}건 · ${fmt(x.w/x.n*100)}% · ${fmt(x.ret/x.n,2)}%</b></div>`).join('')||'<div class="labTiny">데이터 없음</div>';const failRows=fails.map(x=>`<div class="labRow"><span>${esc(x.name)}</span><b>${x.count}회</b></div>`).join('')||'<div class="labTiny">실패 표본 없음</div>';const healthBox=h.fresh?'':`<div class="labCard labHold" style="margin-bottom:10px"><b>${h.status==='STALE'?'⚠ 서버 연구 지연':'⛔ 서버 연구 중단'}</b><div class="labTiny">마지막 계산 ${age(d.generatedAt)} · 저장된 과거 결과는 표시하지만 신규 전략 승격에는 사용하지 않습니다.</div></div>`;
replacePage(p,`<div class="labHero"><div class="row"><div><div class="labTitle">전략 연구소 V2</div><div class="labSub">기존 전략 비교 · 장세별 성과 · 실패원인 · 24H Research/Recovery를 한곳에 모았습니다.</div></div><span class="labBadge">${badge(h.status)}</span></div><div class="labTiny" style="margin-top:7px">마지막 계산 ${age(d.generatedAt)} · ${esc(d.source||'public market data')} · 4H ${d.bars4h||0}봉</div></div>${healthBox}<div class="labGrid"><div class="labCard"><div class="labTiny">서버 누적 신호</div><div class="labMetric">${live.signals||0}건</div><div class="labTiny">4H Forward 평가 ${live.evaluated||0}건${live.winRate==null?'':` · 적중 ${fmt(live.winRate)}%`}</div></div><div class="labCard ${pr.pick?'labPromote':'labHold'}"><div class="labTiny">연구소 판정</div><div class="labMetric">${esc(pr.label)}</div><div class="labTiny">${esc(pr.why)}</div></div><div class="labCard wide" id="strategyComparisonCard"><b>기존 전략 / 후보전략 비교 · 서버 과거 4H 검증</b><div class="labTiny" style="margin-top:4px">이 표가 이전에 보이던 전략 비교 영역입니다.</div><div class="labScroll"><table class="labTable"><thead><tr><th>전략</th><th>표본</th><th>적중률</th><th>평균방향수익</th><th>누적곡선 MDD</th></tr></thead><tbody>${st.length?st.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.n||0}</td><td>${x.win==null?'--':fmt(x.win)+'%'}</td><td>${x.avg==null?'--':fmt(x.avg,2)+'%'}</td><td>${fmt(x.mdd,2)}%</td></tr>`).join(''):'<tr><td colspan="5">전략 데이터 로딩 대기</td></tr>'}</tbody></table></div></div><div class="labCard"><b>시장 국면별 성과</b><div class="labList">${regRows}</div></div><div class="labCard"><b>실패 원인 TOP</b><div class="labList">${failRows}</div></div><div class="labCard wide"><b>자동축적 방식</b><div class="labTiny" style="margin-top:6px">새로 완결된 4H 봉을 독립 표본으로 저장하고 직전 신호의 실제 4H 결과를 판정합니다.</div><button type="button" class="labBtn" id="labRefreshBtn" onclick="return window.BTCStrategyLab.manualRefresh(event)">최신 서버 결과 다시 불러오기</button>${refreshStatusHtml()}</div></div>${auxSlots()}`);afterRender()}
function fetchServer(manual=false){if(BUSY&&manual)return Promise.resolve(SERVER);const before=snapshotKey(SERVER);if(manual){BUSY=true;FETCH_STATE='loading';ERR='';paintRefresh()}const ts=Date.now(),urls=[`./data/research/lab-latest.json?ts=${ts}`,`https://raw.githubusercontent.com/ztman000-bot/btc/main/data/research/lab-latest.json?ts=${ts}`];return Promise.allSettled(urls.map(u=>fetch(u,{cache:'no-store',headers:{'Cache-Control':'no-cache'}}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}))).then(rs=>{const ok=rs.filter(x=>x.status==='fulfilled').map(x=>x.value);if(!ok.length)throw new Error('서버 연구 파일 확인 실패');ok.sort((a,b)=>(Date.parse(b.generatedAt||'')||0)-(Date.parse(a.generatedAt||'')||0));const next=ok[0],changed=!!before&&snapshotKey(next)!==before;SERVER=next;ERR='';LAST_CHECK=Date.now();if(manual){FETCH_STATE=changed?'success':'same';LAST_RESULT=changed?`새 데이터 반영됨 · 서버 계산 ${clock(next.generatedAt)}`:`변경된 연구 결과 없음 · 서버 계산 ${clock(next.generatedAt)}`}return SERVER}).catch(e=>{ERR=String(e?.message||e);LAST_CHECK=Date.now();if(manual)FETCH_STATE='error';return null}).finally(()=>{if(manual){BUSY=false;render();setTimeout(paintRefresh,50)}})}
function manualRefresh(e){try{e?.preventDefault?.();e?.stopPropagation?.()}catch(_){}FETCH_STATE='loading';paintRefresh();fetchServer(true);return false}
function show(){const p=ensurePage();if(!p)return;window.BTCV853?.activatePane?.(p,'research');render();fetchServer(false);window.scrollTo({top:0,behavior:'smooth'})}
function boot(){ensurePage();render();fetchServer(false);setInterval(()=>fetchServer(false),5*60000)}
window.BTCStrategyLab={version:VERSION,show,render,refresh:()=>fetchServer(true),manualRefresh,status:()=>SERVER,health};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();