/* BTC Hedge Assistant - Strategy Research Lab v2.3 server-backed */
(()=>{
'use strict';
const VERSION='2.3',PAGE='strategyLab',$=id=>document.getElementById(id),fmt=(v,d=1)=>v==null||!Number.isFinite(Number(v))?'--':Number(v).toFixed(d),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let SERVER=null,ERR='';
function style(){if($('v2LabStyle'))return;const s=document.createElement('style');s.id='v2LabStyle';s.textContent=`#strategyLab{max-width:980px;margin:0 auto;padding:2px 0 110px}.labHero{background:linear-gradient(180deg,#14243a,#0e1825);border:1px solid #35517a;border-radius:18px;padding:15px;margin-bottom:10px}.labTitle{font-size:23px;font-weight:900}.labSub{font-size:11px;color:#9aa6b2;line-height:1.55;margin-top:5px}.labGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.labCard{background:linear-gradient(180deg,#121b27,#0e1620);border:1px solid #27323f;border-radius:15px;padding:11px}.labCard.wide{grid-column:1/-1}.labMetric{font-size:23px;font-weight:900}.labTiny{font-size:10px;color:#91a0b0;line-height:1.45}.labTable{width:100%;border-collapse:collapse;font-size:10px;min-width:620px}.labTable th,.labTable td{padding:7px;border-bottom:1px solid #223040;text-align:right}.labTable th:first-child,.labTable td:first-child{text-align:left}.labScroll{overflow-x:auto}.labGood{color:#20d792}.labWarn{color:#ffbf47}.labBad{color:#ff667a}.labBadge{display:inline-block;padding:4px 7px;border:1px solid #3a4e66;border-radius:999px;font-size:10px}.labPromote{border-color:#285c48;background:#10271f}.labHold{border-color:#6d5626;background:#2a2111}.labList{display:grid;gap:6px;margin-top:7px}.labRow{display:flex;justify-content:space-between;gap:8px;padding:7px 0;border-bottom:1px solid #223040;font-size:11px}.labBtn{width:100%;margin-top:8px}.labBack{margin-bottom:9px;width:auto}@media(max-width:620px){.labGrid{grid-template-columns:1fr}.labCard.wide{grid-column:auto}}`;document.head.appendChild(s)}
function ensurePage(){style();const main=document.querySelector('main');if(!main)return null;let p=$(PAGE);if(!p){p=document.createElement('section');p.id=PAGE;main.appendChild(p)}if(p.parentElement!==main)main.appendChild(p);p.classList.add('v853Page');p.classList.remove('v852Page','v851Page','tabPane','activePane');if(!p.classList.contains('v853Active'))p.style.display='none';return p}
function localFallback(){let a=[];try{a=window.BTCLearning?.records?.()||JSON.parse(localStorage.getItem('v832learning')||'[]')}catch(e){}const s=a.filter(r=>r?.kind==='scanner_signal'&&r?.outcomes?.['4h']?.hit!=null),w=s.filter(r=>r.outcomes['4h'].hit).length,r=s.map(x=>Number(x.outcomes['4h'].directionalPct)||0);return{n:s.length,win:s.length?w/s.length*100:null,avg:r.length?r.reduce((x,y)=>x+y,0)/r.length:null}}
function health(){const h=window.BTCResearchHealth?.status?.()||window.BTC_RESEARCH_HEALTH;const age=SERVER?.generatedAt?Date.now()-Date.parse(SERVER.generatedAt):Infinity;const st=h?.lab?.status||(age<=5*3600e3?'LIVE':age<=10*3600e3?'STALE':'STOPPED');return{status:st,fresh:st==='LIVE',ageMs:age}}
function promotion(st){const h=health();if(!h.fresh)return{label:'승격 동결',why:'Strategy Lab 데이터가 오래되어 후보 승격을 중지함',pick:null};const cur=st?.[0];if(!cur||cur.n<20)return{label:'데이터 축적 중',why:`서버 평가표본 ${cur?.n||0}건 · 최소 20건 필요`,pick:null};const viable=st.slice(1).filter(x=>x.n>=20&&x.win!=null&&cur.win!=null&&x.win>=cur.win+5&&x.avg!=null&&cur.avg!=null&&x.avg>=cur.avg&&x.mdd>=cur.mdd);if(!viable.length)return{label:'현재 전략 유지',why:'후보가 표본·적중률 +5%p·평균수익·MDD 조건을 동시에 통과하지 못함',pick:null};viable.sort((a,b)=>(b.win-a.win)+(b.avg-a.avg)*2+(b.mdd-a.mdd)*.2);return{label:'승격 후보',why:`${viable[0].name}이 현재 전략보다 우세`,pick:viable[0]}}
function age(ts){if(!ts)return'--';const m=Math.max(0,(Date.now()-new Date(ts).getTime())/60000);return m<60?`${Math.round(m)}분 전`:`${(m/60).toFixed(1)}시간 전`}
function badge(st){return st==='LIVE'?'SERVER LIVE':st==='STALE'?'SERVER STALE':'SERVER STOPPED'}
function backButton(){return '<button class="labBack" id="labBackBtn">‹ 더보기</button>'}
function bindBack(){document.getElementById('labBackBtn')?.addEventListener('click',()=>window.BTCV853?.showMore?.())}
function render(){const p=ensurePage();if(!p)return;if(!SERVER){const l=localFallback();p.innerHTML=backButton()+`<div class="labHero"><div class="labTitle">전략 연구소 V2</div><div class="labSub">서버 4H 자동축적 연결 중 · 앱을 꺼도 GitHub Actions가 독립적으로 연구 데이터를 쌓습니다.</div></div><div class="labGrid"><div class="labCard"><div class="labTiny">로컬 평가</div><div class="labMetric">${l.n}건</div><div class="labTiny">${l.win==null?'평가 대기':`적중 ${fmt(l.win)}% · 평균 ${fmt(l.avg,2)}%`}</div></div><div class="labCard labHold"><div class="labTiny">서버 상태</div><div class="labMetric">${ERR?'연결 점검':'불러오는 중'}</div><div class="labTiny">${esc(ERR||'서버 연구 파일 확인 중')}</div></div></div>`;bindBack();return}
 const d=SERVER,st=Array.isArray(d.strategies)?d.strategies:[],h=health(),pr=promotion(st),live=d.live||{},regs=d.regimes||{},fails=Array.isArray(d.failures)?d.failures:[];const regRows=Object.entries(regs).sort((a,b)=>b[1].n-a[1].n).map(([k,x])=>`<div class="labRow"><span>${esc(k)}</span><b>${x.n}건 · ${fmt(x.w/x.n*100)}% · ${fmt(x.ret/x.n,2)}%</b></div>`).join('')||'<div class="labTiny">데이터 없음</div>';const failRows=fails.map(x=>`<div class="labRow"><span>${esc(x.name)}</span><b>${x.count}회</b></div>`).join('')||'<div class="labTiny">실패 표본 없음</div>';
 const healthBox=h.fresh?'':`<div class="${h.status==='STALE'?'labCard labHold':'labCard'}" style="margin-bottom:10px"><b>${h.status==='STALE'?'⚠ 서버 연구 지연':'⛔ 서버 연구 중단'}</b><div class="labTiny">마지막 계산 ${age(d.generatedAt)} · 저장된 과거 결과는 표시하지만 신규 전략 승격에는 사용하지 않습니다.</div></div>`;
 p.innerHTML=backButton()+`<div class="labHero"><div class="row"><div><div class="labTitle">전략 연구소 V2</div><div class="labSub">완전자동 서버형 · 앱을 꺼도 4H 종가 기준으로 데이터 축적 · 실제 주문 없음</div></div><span class="labBadge">${badge(h.status)}</span></div><div class="labTiny" style="margin-top:7px">마지막 계산 ${age(d.generatedAt)} · ${esc(d.source||'public market data')} · 4H ${d.bars4h||0}봉</div></div>${healthBox}<div class="labGrid"><div class="labCard"><div class="labTiny">서버 누적 신호</div><div class="labMetric">${live.signals||0}건</div><div class="labTiny">4H Forward 평가 ${live.evaluated||0}건${live.winRate==null?'':` · 적중 ${fmt(live.winRate)}%`}</div></div><div class="labCard ${pr.pick?'labPromote':'labHold'}"><div class="labTiny">연구소 판정</div><div class="labMetric">${esc(pr.label)}</div><div class="labTiny">${esc(pr.why)}</div></div><div class="labCard wide"><b>현재전략 vs 후보전략 · 서버 과거 4H 검증</b><div class="labScroll"><table class="labTable"><thead><tr><th>전략</th><th>표본</th><th>적중률</th><th>평균방향수익</th><th>누적곡선 MDD</th></tr></thead><tbody>${st.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${x.n||0}</td><td>${x.win==null?'--':fmt(x.win)+'%'}</td><td>${x.avg==null?'--':fmt(x.avg,2)+'%'}</td><td>${fmt(x.mdd,2)}%</td></tr>`).join('')}</tbody></table></div></div><div class="labCard"><b>시장 국면별 성과</b><div class="labList">${regRows}</div></div><div class="labCard"><b>실패 원인 TOP</b><div class="labList">${failRows}</div></div><div class="labCard wide"><b>자동축적 방식</b><div class="labTiny" style="margin-top:6px">서버가 새로운 완결 4H 봉을 독립 표본으로 저장하고 직전 신호의 실제 4H 결과를 판정합니다. 5시간 이상 갱신이 없으면 STALE로 전환해 승격을 동결합니다.</div><button class="labBtn" id="labRefreshBtn">최신 서버 결과 다시 불러오기</button></div></div>`;bindBack();$('#labRefreshBtn')?.addEventListener('click',fetchServer)}
function fetchServer(){const urls=['./data/research/lab-latest.json?ts='+Date.now(),'https://raw.githubusercontent.com/ztman000-bot/btc/main/data/research/lab-latest.json?ts='+Date.now()];Promise.allSettled(urls.map(u=>fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}))).then(rs=>{const ok=rs.filter(x=>x.status==='fulfilled').map(x=>x.value);if(!ok.length)throw new Error('서버 연구 파일 확인 실패');ok.sort((a,b)=>(Date.parse(b.generatedAt||'')||0)-(Date.parse(a.generatedAt||'')||0));SERVER=ok[0];ERR='';render()}).catch(e=>{ERR=String(e?.message||e);render()})}
function show(){const p=ensurePage();if(!p)return;if(window.BTCV853?.activatePane)window.BTCV853.activatePane(p,'more');else{document.querySelectorAll('main>.v853Page,main>.v852Page,main>.v851Page,main>.tabPane').forEach(x=>{if(x!==p){x.style.display='none';x.classList.remove('v853Active','activePane')}});p.style.display='block';p.classList.add('v853Active')}render();fetchServer();window.scrollTo({top:0,behavior:'smooth'})}
function boot(){ensurePage();render();fetchServer();setInterval(fetchServer,5*60000);document.addEventListener('btc-research-health',()=>setTimeout(render,20))}
window.BTCStrategyLab={version:VERSION,show,render,refresh:fetchServer,status:()=>SERVER,health};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();