const SELF_URL=new URL(self.location.href);
const APP_VERSION='8.24.6';
const C='btc-hedge-v'+APP_VERSION.replace(/[^0-9A-Za-z._-]/g,'-')+'-canonical';
const APP_SCRIPTS=['learning.js','updater.js','dailybrief.js','dailybrief-fix.js','v850-shell.js','version-guard.js','app-config.js','performance-core.js','v8223-ui.js','stability-cleanup.js','reliability-core.js','scanner-network-fix.js','scanner-hotfix-v8224.js','scanner-hotfix-v8225.js','scanner-batch-v8231.js','scanner-selection-fix-v8233.js','scanner-ui-repair-v8241.js','chart-resume-fix-v8242.js','chart-theme-v8243.js','chart-timeframes-v8246.js','stock-relay-fast-v8234.js','top10-fast-v8232.js','trade-ladder-ui-v8236.js','strategy-lab.js','strategy-position.js','auto-top10.js','top10-history.js','opportunity-v2.js','smart-session.js','dynamic-hedge.js','cycle-hedge.js','regime-hedge.js','path-ensemble.js','recovery-engine.js','adaptive-learning.js','execution-exit.js','strategy-governance.js','market-structure.js','terminal-wallet.js','mobile-layout-fix.js','safety-core.js','research-health.js','research-shadow.js','recovery-v2-ui.js','reversal-intelligence.js','hedge-rotation.js','stability-guard.js','startup-health.js','globalbrief.js','globalbrief-v868.js','safety-health.js','today-analysis.js'];
const JSONS=['/data/daily/brief.json','/data/daily/global.json','/data/backtests/hedge_strategy.json','/data/research/latest.json','/data/research/shadow-history.json','/data/research/config.json','/data/research/lab-latest.json','/data/research/research-heartbeat.json','/data/research/regime-state.json'];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(C))});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('btc-hedge-v')&&k!==C).map(k=>caches.delete(k)));await self.clients.claim()})())});
async function timedFetch(req,ms=6000){const ctl=new AbortController();const t=setTimeout(()=>ctl.abort(),ms);try{return await fetch(req,{cache:'no-store',signal:ctl.signal})}finally{clearTimeout(t)}}
async function networkFirst(req){const c=await caches.open(C);try{const r=await timedFetch(req,6000);if(r&&r.ok)await c.put(req,r.clone());return r}catch(e){const hit=await c.match(req);return hit||Response.error()}}
async function cacheFirst(req){const c=await caches.open(C);const hit=await c.match(req);if(hit){timedFetch(req,6000).then(r=>{if(r&&r.ok)c.put(req,r.clone())}).catch(()=>{});return hit}try{const r=await timedFetch(req,6000);if(r&&r.ok)await c.put(req,r.clone());return r}catch(e){return Response.error()}}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url),isDoc=e.request.mode==='navigate'||e.request.destination==='document';if(isDoc||APP_SCRIPTS.some(n=>u.pathname.endsWith('/'+n))||JSONS.some(p=>u.pathname.endsWith(p))){e.respondWith(networkFirst(e.request));return}e.respondWith(cacheFirst(e.request))});