/* BTC Hedge Assistant v8.20.0 - Fast Local Terminal Wallet Estimate + Central Safety Gate */
(()=>{'use strict';
const V='8.20.0',$=id=>document.getElementById(id),N=v=>Number.isFinite(Number(v))?Number(v):null,clamp=(x,a,b)=>Math.max(a,Math.min(b,x));let LAST=null;
function M(){try{return typeof market!=='undefined'?market:(window.market||{})}catch(e){return window.market||{}}}
function P(){try{return typeof pos==='function'?pos():(window.pos?.())}catch(e){return null}}
function price(){return Number(M()?.price)||Number((M()?.h4||[]).at(-1)?.[4])||0}
function rows(){const a=M()?.h4||[];return Array.isArray(a)?a:[]}
function atrPct(){const a=rows();if(a.length<20)return .03;let tr=[];for(let i=1;i<a.length;i++){const hi=Number(Array.isArray(a[i])?a[i][2]:a[i].high),lo=Number(Array.isArray(a[i])?a[i][3]:a[i].low),pc=Number(Array.isArray(a[i-1])?a[i-1][4]:a[i-1].close);if([hi,lo,pc].every(Number.isFinite))tr.push(Math.max(hi-lo,Math.abs(hi-pc),Math.abs(lo-pc)))}const x=tr.slice(-14),p=price()||1;return x.length?x.reduce((s,v)=>s+v,0)/x.length/p:.03}
function feeRate(d){return (N(d?.feeRate)||.04)/100}
function reality(d){try{return window.BTCExecutionExit?.reality?.(d)||null}catch(e){return null}}
function oneWay(d){const r=reality(d);return r?.oneWay||Math.max(.0006,feeRate(d)+.0002)}
function baseState(d){return{wallet:N(d.wallet)||0,added:N(d.added)||0,lq:N(d.lq)||0,sq:N(d.sq)||0}}
function apply(state,d,p,action){let s={...state},q=0,rate=oneWay(d);if(action.side==='SHORT'){q=Math.min(action.qty,s.sq);s.wallet+=(N(d.se)-p)*q-p*q*rate;s.sq-=q}else if(action.side==='LONG'){q=Math.min(action.qty,s.lq);s.wallet+=(p-N(d.le))*q-p*q*rate;s.lq-=q}else if(action.side==='ALL'){s.wallet+=(p-N(d.le))*s.lq+(N(d.se)-p)*s.sq-p*(s.lq+s.sq)*rate;s.lq=0;s.sq=0}return{...s,actionQty:q,cost:p*q*rate}}
function terminalWallet(s,d,pEnd,ms){let w=s.wallet+s.added+s.lq*(pEnd-N(d.le))+s.sq*(N(d.se)-pEnd)-pEnd*(s.lq+s.sq)*oneWay(d);if(ms?.healthy&&Number.isFinite(ms.funding))w+=(s.sq-s.lq)*pEnd*ms.funding*3;return w}
function mmr(d){if(window.BTCSafetyCore?.mmr)return window.BTCSafetyCore.mmr(d);if(!d?.liq||(!(N(d.lq))&&!(N(d.sq))))return null;const liq=N(d.liq),q=(N(d.wallet)||0)+(N(d.added)||0)+(N(d.lq)||0)*(liq-N(d.le))+(N(d.sq)||0)*(N(d.se)-liq),n=((N(d.lq)||0)+(N(d.sq)||0))*liq;return n?q/n:null}
function liqFor(s,d,m){if(window.BTCSafetyCore?.liqFor)return window.BTCSafetyCore.liqFor(s,d,m);if(m==null)return NaN;const den=(s.lq-s.sq)-m*(s.lq+s.sq),num=s.wallet+s.added-s.lq*N(d.le)+s.sq*N(d.se);return Math.abs(den)<1e-10?NaN:-num/den}
function safeDist(s,d,p){if(window.BTCSafetyCore?.distance)return window.BTCSafetyCore.distance(d,p,s);const l=liqFor(s,d,mmr(d));return(!Number.isFinite(l)||l<=0)?1e12:Math.abs(l-p)}
function centralGuard(){try{return Math.max(10000,Number(window.BTCSafetyCore?.current?.()?.operating)||10000)}catch(e){return 10000}}
function systemAllowed(){return window.BTC_DECISION_ALLOWED!==false&&!!window.BTCSafetyCore}
function regime(){try{return window.BTCRegimeHedge?.trendScore?.()?.score??50}catch(e){return 50}}
function optimizer(){try{return window.BTCAdaptiveLearning?.recommendation?.()||null}catch(e){return null}}
function structure(){try{return window.BTCMarketStructure?.status?.()||null}catch(e){return null}}
function executionReady(){const txt=String($('conditionScore')?.textContent||''),m=txt.match(/(\d+)\s*\/\s*(\d+)/),act=String($('nextNow')?.textContent||'');return{ready:!!m&&+m[1]>=+m[2]&&!/관망|대기|보류/.test(act),action:act}}
function scenarios(p,rg,opt,ms){const a=Math.max(.015,atrPct()),blend=clamp(((rg-50)/50)*.65+(opt?.healthy?((.5-opt.shortKeep)-(.5-opt.longKeep))*.35:0)+(ms?.healthy?ms.bias:0),-1,1),ks=[-3,-2,-1,0,1,2,3],raw=ks.map(k=>Math.exp(k*blend*.7)),z=raw.reduce((s,x)=>s+x,0);return ks.map((k,i)=>({k,p:Math.max(1000,p*(1+k*a)),w:raw[i]/z}))}
function actions(d){return[{id:'HOLD',label:'그대로 유지',side:'NONE',qty:0},{id:'S025',label:'숏 0.025 축소',side:'SHORT',qty:.025},{id:'S050',label:'숏 0.050 축소',side:'SHORT',qty:.05},{id:'L025',label:'롱 0.025 축소',side:'LONG',qty:.025},{id:'L050',label:'롱 0.050 축소',side:'LONG',qty:.05},{id:'EXIT',label:'양 포지션 전량종료',side:'ALL',qty:0}].filter(a=>a.side==='NONE'||a.side==='ALL'||(a.side==='SHORT'?(N(d.sq)||0)>0:(N(d.lq)||0)>0))}
function evaluateAction(a,d,p,sc,ms,target){const s=apply(baseState(d),d,p,a),safe=safeDist(s,d,p),need=centralGuard(),vals=sc.map(x=>({w:terminalWallet(s,d,x.p,ms),prob:x.w,p:x.p,k:x.k})),exp=vals.reduce((z,x)=>z+x.w*x.prob,0),sorted=[...vals].sort((x,y)=>x.w-y.w),worst=sorted[0]?.w??-Infinity,p10=sorted[Math.min(sorted.length-1,1)]?.w??worst,recovery=vals.reduce((z,x)=>z+(x.w>=target?x.prob:0),0),utility=exp+.20*p10+.10*worst-2000*Math.max(0,.10-recovery);return{...a,state:s,safe,need,exp,worst,p10,recovery,utility,vals,valid:a.side==='ALL'||a.side==='NONE'||safe>=need}}
function decide(){const d=P(),p=price();if(!d||!p)return null;const rg=regime(),opt=optimizer(),ms=structure(),sc=scenarios(p,rg,opt,ms),target=N(d.wallet)||69936.30,all=actions(d).map(a=>evaluateAction(a,d,p,sc,ms,target)).filter(x=>x.valid).sort((a,b)=>b.utility-a.utility),best=all[0],hold=all.find(x=>x.id==='HOLD')||best,gate=executionReady(),gov=opt?.governanceApproved!==false,exitRec=window.BTCExecutionExit?.recommendation?.()?.ex||null;let executable=best,reason='로컬 7-노드 위험조정 Terminal Wallet 1위';if(!systemAllowed()){executable=hold;reason='Central Safety / Runtime Health 미통과 → 관망'}else if(best&&best.id!=='HOLD'&&best.id!=='EXIT'&&(!gate.ready||!gov)){executable=hold;reason=!gov?'Governance 미승인 → 관망':'실행조건 미충족 → 관망'}if(best?.id==='EXIT'&&!(exitRec?.code==='EXIT'||exitRec?.code==='LOCK'||terminalWallet(baseState(d),d,p,ms)>=target)){executable=hold;reason='전량종료는 Recovery/Exit 조건 미충족 → 관망'}LAST={version:V,d,p,rg,opt,ms,sc,target,all,best,hold,executable,reason,gate,gov,guard:centralGuard(),systemAllowed:systemAllowed(),at:Date.now()};render();return LAST}
function pane(){return $('v850HomePane')||document.querySelector('main>.v853Active')||document.querySelector('main')}
function ensure(){let c=$('terminalWalletCard');if(!c){c=document.createElement('div');c.id='terminalWalletCard';c.className='card'}const p=pane();if(p&&c.parentElement!==p){const a=$('executionExitCard')||$('marketStructureCard')||$('strategyGovernanceCard');if(a&&a.parentElement===p)a.insertAdjacentElement('afterend',c);else p.appendChild(c)}c.classList.remove('v853Page','v852Page','v851Page','tabPane');c.style.cssText+=';display:block;width:100%;max-width:100%;min-width:0';return c}
const money=x=>Number.isFinite(x)?'$'+Math.round(x).toLocaleString():'--',pct=x=>Number.isFinite(x)?(x*100).toFixed(1)+'%':'--';
function render(){const c=ensure();if(!c)return;const d=LAST;if(!d){c.innerHTML=`<div class="row"><b>🧮 Fast Local Terminal Wallet Estimate</b><span class="badge">v${V}</span></div><div class="small">포지션·Optimizer·Execution 데이터 대기 중...</div>`;return}const x=d.executable,b=d.best,delta=x.exp-d.hold.exp,tone=!d.systemAllowed?'notice':x.id==='HOLD'?'warnbox':x.id==='EXIT'?'notice':'okbox';c.innerHTML=`<div class="row"><div><b>🧮 Fast Local Terminal Wallet Estimate</b><div class="small">7개 ATR 시나리오의 빠른 로컬 추정 · 서버 3000-path MC는 Recovery 2.0이 Primary</div></div><span class="badge">v${V}</span></div><div class="${tone}" style="margin-top:8px"><b style="font-size:18px">${x.id==='HOLD'?'🟡 로컬 추천: 관망':x.id==='EXIT'?'🔵 로컬 추천: 전량종료 검토':`🟢 로컬 추천: ${x.label}`}</b><br>${d.reason}</div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">추천 기대 Wallet</div><b>${money(x.exp)}</b></div><div class="kpi"><div class="small">HOLD 대비</div><b>${delta>=0?'+':''}${money(delta).replace('$','')}</b></div><div class="kpi"><div class="small">Recovery 성공확률</div><b>${pct(x.recovery)}</b></div></div><div class="grid3" style="margin-top:8px"><div class="kpi"><div class="small">최악 시나리오</div><b>${money(x.worst)}</b></div><div class="kpi"><div class="small">중앙 Guard 거리</div><b>${x.safe>1e10?'--':money(x.safe)}</b><div class="tiny">필요 ${money(d.guard)}</div></div><div class="kpi"><div class="small">모델 1위</div><b>${b.label}</b></div></div><details style="margin-top:9px"><summary class="small"><b>행동별 로컬 비교</b></summary><div style="margin-top:8px">${d.all.slice(0,6).map(a=>`<div class="kpi" style="margin-bottom:6px"><b>${a.label}</b><div class="tiny">기대 ${money(a.exp)} · 최악 ${money(a.worst)} · 회복 ${pct(a.recovery)} · 거리 ${a.safe>1e10?'--':money(a.safe)}</div></div>`).join('')}</div></details><div class="tiny" style="margin-top:7px">이 카드는 빠른 로컬 안전 추정입니다. 최종 연구 우선순위는 서버 3000-path Monte Carlo → Governance → Central Safety Guard → 실행조건 순서입니다.</div>`}
function boot(){setTimeout(decide,500);[1800,5000,9000].forEach(x=>setTimeout(decide,x));setInterval(decide,60000);document.addEventListener('btc-adaptive-ready',()=>setTimeout(decide,80));document.addEventListener('btc-market-structure-ready',()=>setTimeout(decide,80));document.addEventListener('btc-system-health',()=>setTimeout(decide,80));document.addEventListener('btc-safety-core',()=>setTimeout(decide,80))}window.BTCTerminalWallet={version:V,decide,status:()=>LAST};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();