/* BTC Hedge Assistant v8.22.2 - Compact Home + 13-Tool Dock + Health Guard */
(()=>{
'use strict';
if(window.__BTC_V8222_SHELL_SINGLETON&&window.BTCV8222)return;
window.__BTC_V8222_SHELL_SINGLETON=true;
const FALLBACK_VERSION='8.22.2';
const $=id=>document.getElementById(id);
const ROUTES=[
  ['home','⌂','홈'],['scanner','⌕','스캐너'],['position','◫','포지션'],['trade','⇄','실전표'],['chart','⌁','차트'],['risk','⚠','리스크'],['research','⌬','연구소'],
  ['analysis','◎','종합분석'],['daily','☼','일일'],['settings','⚙','설정'],['alerts','◉','알림'],['backtest','↺','백테스트'],['log','≡','기록']
];
const LEGACY_TOOL_IDS=['scanner','position','trade','settings','alerts','backtest','log','strategyLab','dailyBriefPane'];
function version(){return window.BTC_APP_CONFIG?.version||window.BTC_APP_VERSION||FALLBACK_VERSION}
function loadScript(id,src){if(document.getElementById(id))return Promise.resolve(document.getElementById(id));return new Promise((resolve,reject)=>{const s=document.createElement('script');s.id=id;s.src=src;s.async=false;s.onload=()=>resolve(s);s.onerror=()=>reject(new Error('load failed: '+src));document.head.appendChild(s)})}
async function ensureCanonicalBootstrap(){try{if(!window.BTC_APP_CONFIG)await loadScript('btcAppConfigShell','./app-config.js?v='+FALLBACK_VERSION+'&ts='+Date.now());if(!window.BTCBootstrap)await loadScript('btcVersionGuardShell','./version-guard.js?v='+version()+'&ts='+Date.now());await window.BTCBootstrap?.boot?.()}catch(e){console.warn('[BTC v8.22.2 bootstrap]',e)}}
function injectStyle(){
  if($('v8222Style'))return;const s=document.createElement('style');s.id='v8222Style';s.textContent=`
body.v8222{padding-bottom:108px!important}body.v8222 main{max-width:980px!important;padding:10px!important}body.v8222 main>*{display:none!important}body.v8222 main>.v8222Page.v8222Active,body.v8222 main>.v8221Page.v8222Active{display:block!important}body.v8222 .topTabsSticky,body.v8222 .v82TabsHint{display:none!important}
#v8222HomePane,#v8222ChartPage,#v8222RiskPage{padding:0 0 18px}#v8222HomePane .v8222HomeTitle{margin:2px 2px 10px;padding:12px 14px;border:1px solid #35517a;border-radius:16px;background:linear-gradient(180deg,#14243a,#0e1825)}#v8222HomePane .v8222HomeTitle b{display:block;font-size:18px}.v8222HomeTitle span{display:block;color:#9aa6b2;font-size:11px;margin-top:4px;line-height:1.45}
#v8222HomePane #conditionList,#v8222HomePane #readinessBox,#v8222HomePane #tfConfidence,#v8222HomePane #blockers,#v8222HomePane #actionReason,#v8222HomePane #riskGate{display:none!important}#v8222HomePane .nextActionCard{padding:12px!important}#v8222HomePane .nextMain{font-size:21px!important}#v8222HomePane .card,#v8222HomePane .grid3{margin-bottom:9px!important}
.v8222SectionHead{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:4px 2px 10px}.v8222SectionHead b{font-size:17px}.v8222SectionHead span{font-size:10px;color:#8fa0b5}
.v8222HealthBadge{position:fixed;right:10px;bottom:94px;z-index:101;border:1px solid #35517a;border-radius:999px;padding:4px 8px;background:#0b1622e8;font-size:9px;color:#c7d2df;pointer-events:none}.v8222HealthBadge.good{border-color:#285c48;color:#9ff0cf}.v8222HealthBadge.warn{border-color:#715625;color:#ffd486}.v8222HealthBadge.bad{border-color:#713e47;color:#ffabb6}
footer.v8222Dock{position:fixed!important;left:0;right:0;bottom:0;z-index:100!important;display:grid!important;grid-template-columns:repeat(7,minmax(0,1fr))!important;gap:2px!important;padding:5px 5px max(6px,env(safe-area-inset-bottom))!important;background:#0b1118f7!important;border-top:1px solid #27323f!important;backdrop-filter:blur(10px)}footer.v8222Dock button{min-width:0!important;min-height:40px!important;padding:3px 0!important;border-radius:9px!important;background:transparent!important;border:1px solid transparent!important;color:#9eabba!important;font-size:8px!important;line-height:1.05!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important}footer.v8222Dock button i{font-style:normal;font-size:15px;line-height:1}footer.v8222Dock button b{font-size:8px;white-space:nowrap}footer.v8222Dock button.active{background:#172a46!important;border-color:#315a91!important;color:#f2f7ff!important}
.v8222Fallback{border:1px solid #30445a;border-radius:14px;background:#0d1722;padding:15px;line-height:1.55;color:#b8c6d5}@media(max-width:520px){body.v8222{padding-bottom:104px!important}.v8222HealthBadge{bottom:90px}footer.v8222Dock button{min-height:38px!important}#v8222HomePane .grid3{grid-template-columns:1fr 1fr!important}#v8222HomePane .grid3>.card:last-child{grid-column:1/-1}}
`;document.head.appendChild(s)
}
function patchVersion(){const v=version();document.title='BTC Hedge Assistant v'+v;document.querySelectorAll('h1').forEach(h=>{if(/BTC Hedge Assistant/i.test(h.textContent||''))h.textContent='BTC Hedge Assistant v'+v});window.BTC_APP_VERSION=v}
function section(id,title,sub=''){let p=$(id);if(!p){p=document.createElement('section');p.id=id;p.className='v8222Page';p.innerHTML=`<div class="v8222SectionHead"><b>${title}</b><span>${sub}</span></div>`;document.querySelector('main')?.appendChild(p)}p.classList.add('v8222Page');return p}
function ensureStructure(){
  const main=document.querySelector('main');if(!main)return false;
  let home=$('v8222HomePane');if(!home){home=document.createElement('section');home.id='v8222HomePane';home.className='v8222Page v8222Active';home.innerHTML=`<div class="v8222HomeTitle"><b>핵심 대시보드</b><span>현재가 · 다음 행동 · 안전거리 · 전략 상태 · 시장 국면만 요약합니다. 상세 설명은 하단 ‘종합분석’에서 확인하세요.</span></div>`;main.insertBefore(home,main.firstChild)}
  const status=$('marketStatus')?.closest('.card'),priceGrid=$('price')?.closest('.grid3'),next=$('nextNow')?.closest('.nextActionCard'),signal=$('strategyState')?.closest('.card'),regime=$('marketRegime')?.closest('.card');[status,priceGrid,next,signal,regime].forEach(el=>{if(el&&el.parentElement!==home)home.appendChild(el)});
  const risk=section('v8222RiskPage','리스크 / 안전관리','스트레스·안전거리·증거금 효율');['sensitivityStats','stressGrid','distanceStats','marginScenarios','riskEfficiency'].forEach(id=>{const top=$(id)?.closest('.card');if(top&&top.parentElement!==risk)risk.appendChild(top)});
  const chartPage=section('v8222ChartPage','BTC 차트','가격·지표·포지션 레벨');const chartCard=$('chart')?.closest('.card');if(chartCard&&chartCard.parentElement!==chartPage)chartPage.appendChild(chartCard);const info=$('tf1h')?.closest('.infoGrid');if(info&&info.parentElement!==chartPage)chartPage.appendChild(info);
  LEGACY_TOOL_IDS.forEach(id=>{const el=$(id);if(el){el.classList.add('v8222Page');el.classList.remove('activePane');el.style.removeProperty('display')}});$('v8222TodayAnalysisPage')?.classList.add('v8222Page');
  document.querySelectorAll('main>.tabs,main>.v82TabsHint').forEach(x=>x.remove());return true
}
function activeButton(route){document.querySelectorAll('footer.v8222Dock button').forEach(b=>b.classList.toggle('active',b.dataset.route===route))}
function activate(el,route){if(!el)return false;ensureStructure();document.querySelectorAll('main>.v8222Page,main>.v8221Page').forEach(x=>{x.classList.remove('v8222Active','v8221Active','activePane');x.style.removeProperty('display')});el.classList.add('v8222Active');if(el.classList.contains('tabPane'))el.classList.add('activePane');activeButton(route);if(location.hash!=='#'+route)history.replaceState(null,'','#'+route);requestAnimationFrame(()=>{window.scrollTo({top:0,behavior:'auto'});if(route==='chart')try{window.drawChart?.()}catch(e){}});return true}
function direct(id,route){return activate($(id),route)}
function showHome(){ensureStructure();return activate($('v8222HomePane'),'home')}
function showChart(){ensureStructure();return activate($('v8222ChartPage'),'chart')}
function showRisk(){ensureStructure();return activate($('v8222RiskPage'),'risk')}
function showDaily(attempt=0){const p=$('dailyBriefPane');if(p){p.classList.add('v8222Page');return activate(p,'daily')}if(attempt<12){ensureCanonicalBootstrap();return setTimeout(()=>showDaily(attempt+1),250)}return showFallback('daily','일일 시황','일일 시황 모듈을 불러오지 못했습니다. 새로고침 후 다시 확인하세요.')}
function showResearch(attempt=0){const p=$('strategyLab');if(p){p.classList.add('v8222Page');const ok=activate(p,'research');try{window.BTCStrategyLab?.render?.()}catch(e){}return ok}if(attempt<12){ensureCanonicalBootstrap();return setTimeout(()=>showResearch(attempt+1),250)}return showFallback('research','전략 연구소','전략 연구소 모듈을 불러오지 못했습니다. 시스템 초기화 상태를 확인하세요.')}
async function showAnalysis(attempt=0){if(window.BTCTodayAnalysis?.render){const p=window.BTCTodayAnalysis.page();p.classList.add('v8222Page');activate(p,'analysis');await window.BTCTodayAnalysis.render();return true}if(attempt<12){await ensureCanonicalBootstrap();return new Promise(resolve=>setTimeout(()=>resolve(showAnalysis(attempt+1)),200))}return showFallback('analysis','금일의 종합분석','종합분석 모듈을 불러오지 못했습니다. 안전 상태와 네트워크를 확인하세요.')}
function showFallback(route,title,msg){const p=section('v8222FallbackPage',title,'모듈 상태');p.innerHTML=`<div class="v8222SectionHead"><b>${title}</b><span>모듈 상태</span></div><div class="v8222Fallback">${msg}<div style="margin-top:10px"><button type="button" id="v8222Retry">다시 불러오기</button></div></div>`;p.querySelector('#v8222Retry')?.addEventListener('click',()=>{ensureCanonicalBootstrap().then(()=>routeTo(route))});return activate(p,route)}
function routeTo(route){switch(route){case'home':return showHome();case'scanner':return direct('scanner','scanner')||showHome();case'position':return direct('position','position')||showHome();case'trade':return direct('trade','trade')||showHome();case'chart':return showChart();case'risk':return showRisk();case'research':return showResearch();case'analysis':return showAnalysis();case'daily':return showDaily();case'settings':return direct('settings','settings')||showHome();case'alerts':return direct('alerts','alerts')||showHome();case'backtest':return direct('backtest','backtest')||showHome();case'log':return direct('log','log')||showHome();default:return showHome()}}
function buildDock(){let f=document.querySelector('footer');if(!f){f=document.createElement('footer');document.body.appendChild(f)}f.className='v8222Dock';f.innerHTML=ROUTES.map(([r,i,l])=>`<button type="button" data-route="${r}" aria-label="${l}"><i>${i}</i><b>${l}</b></button>`).join('');f.querySelectorAll('button').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();routeTo(b.dataset.route)}))}
function patchLegacyNavigation(){window.openTab=id=>routeTo(({scanner:'scanner',position:'position',trade:'trade',settings:'settings',alerts:'alerts',backtest:'backtest',log:'log'})[id]||'home');window.BTCV853={version:FALLBACK_VERSION,route:routeTo,activatePane:activate,showHome,showDaily,showMore:showHome,openTool:id=>routeTo(id==='strategyLab'?'research':id),adoptModernHome:ensureStructure,adoptCanonicalHome:ensureStructure,normalizeStrategyLab:()=>{},ensureResearchSlot:()=>null,ensureHomeSlots:()=>({}),slot:()=>null}}
function patchOutcomeBug(){window.v80UpdateOutcomes=function(r){let arr=window.v80LoadPerf?window.v80LoadPerf(r):[],changed=false;for(const x of arr){if(!x?.t||!x?.price)continue;if(x.h1==null){let c=window.v83NearestClose?.(r.h1?.rows||r.raw?.h1||r.h1,x.t+3600000,4200000),v=window.v83OutcomePct?.(Number(x.price),c);if(v!=null){x.h1=v;changed=true}}if(x.h4==null){let c=window.v83NearestClose?.(r.h4?.rows||r.raw?.h4||r.h4,x.t+14400000,9000000),v=window.v83OutcomePct?.(Number(x.price),c);if(v!=null){x.h4=v;changed=true}}if(x.h24==null){let c=window.v83NearestClose?.(r.h1?.rows||r.raw?.h1||r.h1,x.t+86400000,5400000),v=window.v83OutcomePct?.(Number(x.price),c);if(v!=null){x.h24=v;changed=true}}}if(changed)window.v80SavePerf?.(r,arr);return arr}}
function registerCurrentSW(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('./sw.js?v='+encodeURIComponent(version()),{updateViaCache:'none'}).then(r=>r.update()).catch(e=>window.BTCSafetyHealth?.record?.('service-worker',e.message,'shell'))}
function ensureHealthBadge(){let b=$('v8222HealthBadge');if(!b){b=document.createElement('div');b.id='v8222HealthBadge';b.className='v8222HealthBadge';b.textContent='HEALTH CHECK';document.body.appendChild(b)}return b}
function renderHealth(e){const h=e?.detail||window.BTC_SAFETY_HEALTH,b=ensureHealthBadge();if(!h){b.textContent='HEALTH CHECK';b.className='v8222HealthBadge';return}b.textContent=h.grade==='HEALTHY'?'SYSTEM OK':h.grade==='CRITICAL'?'SYSTEM CRITICAL':'SYSTEM WARN';b.className='v8222HealthBadge '+(h.grade==='HEALTHY'?'good':h.grade==='CRITICAL'?'bad':'warn')}
function observeModules(){const main=document.querySelector('main');if(!main||window.__BTC_V8222_OBSERVER)return;window.__BTC_V8222_OBSERVER=new MutationObserver(()=>{LEGACY_TOOL_IDS.forEach(id=>$(id)?.classList.add('v8222Page'));$('v8222TodayAnalysisPage')?.classList.add('v8222Page');patchVersion()});window.__BTC_V8222_OBSERVER.observe(main,{childList:true})}
async function init(){injectStyle();document.body.classList.remove('v851','v852','v853','v8221');document.body.classList.add('v8222');patchOutcomeBug();buildDock();ensureStructure();patchLegacyNavigation();patchVersion();observeModules();ensureHealthBadge();registerCurrentSW();ensureCanonicalBootstrap().then(()=>{patchVersion();ensureStructure();window.BTCSafetyHealth?.check?.().then(renderHealth).catch(()=>{})});const h=(location.hash||'#home').slice(1);routeTo(ROUTES.some(x=>x[0]===h)?h:'home')}
document.addEventListener('btc-safety-health',renderHealth);window.addEventListener('hashchange',()=>{const h=(location.hash||'#home').slice(1);if(ROUTES.some(x=>x[0]===h))routeTo(h)});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80),{once:true});else setTimeout(init,80);
window.BTCV8222={version:FALLBACK_VERSION,route:routeTo,showHome,showChart,showRisk,showDaily,showResearch,showAnalysis,activate,ensureStructure,ensureCanonicalBootstrap,routes:[...ROUTES]};window.BTCV8221=window.BTCV8222;
})();