/* BTC Hedge Assistant - deterministic bootstrap + canonical version source */
(function(){'use strict';
var loaded={},booted=false,versionObserver=null;
function load(id,src){return new Promise(function(resolve,reject){var old=document.getElementById(id);if(old){resolve(old);return}var s=document.createElement('script');s.id=id;s.src=src;s.async=false;s.onload=function(){loaded[id]=true;resolve(s)};s.onerror=function(){reject(new Error('load failed: '+src))};document.head.appendChild(s)})}
function applyVersion(){var cfg=window.BTC_APP_CONFIG||{},v=cfg.version||window.BTC_APP_VERSION||'unknown',title=(cfg.name||'BTC Hedge Assistant')+' v'+v;document.title=title;var hs=document.querySelectorAll('h1');for(var i=0;i<hs.length;i++){if(/BTC Hedge Assistant/i.test(hs[i].textContent||''))hs[i].textContent=title}document.documentElement.dataset.btcAppVersion=v;window.BTC_APP_VERSION=v;return v}
function retryVersion(){[0,120,450,1200,3000,7000,12000].forEach(function(ms){setTimeout(applyVersion,ms)})}
function watchVersion(){if(versionObserver||!window.MutationObserver)return;var header=document.querySelector('header')||document.body;if(!header)return;versionObserver=new MutationObserver(function(){var cfg=window.BTC_APP_CONFIG||{},v=cfg.version||window.BTC_APP_VERSION;if(!v)return;var expected=(cfg.name||'BTC Hedge Assistant')+' v'+v,hs=document.querySelectorAll('h1'),wrong=document.title!==expected;for(var i=0;i<hs.length&&!wrong;i++){if(/BTC Hedge Assistant/i.test(hs[i].textContent||'')&&hs[i].textContent!==expected)wrong=true}if(wrong)applyVersion()});versionObserver.observe(header,{subtree:true,childList:true,characterData:true});}
function boot(){if(booted)return;booted=true;load('btcAppConfig','./app-config.js?ts='+Date.now()).then(function(){applyVersion();retryVersion();watchVersion();return load('btcSafetyCore','./safety-core.js?v='+encodeURIComponent(window.BTC_APP_VERSION||'')+'&ts='+Date.now())}).then(function(){return load('btcResearchHealthScript','./research-health.js?v='+encodeURIComponent(window.BTC_APP_VERSION||'')+'&ts='+Date.now())}).then(function(){return load('btcRecoveryV2Ui','./recovery-v2-ui.js?v='+encodeURIComponent(window.BTC_APP_VERSION||'')+'&ts='+Date.now())}).then(function(){return load('btcReversalIntelligence','./reversal-intelligence.js?v='+encodeURIComponent(window.BTC_APP_VERSION||'')+'&ts='+Date.now())}).then(function(){return load('btcHedgeRotation','./hedge-rotation.js?v='+encodeURIComponent(window.BTC_APP_VERSION||'')+'&ts='+Date.now())}).then(function(){return load('btcStartupHealthScript','./startup-health.js?v='+encodeURIComponent(window.BTC_APP_VERSION||'')+'&ts='+Date.now())}).then(function(){applyVersion()}).catch(function(e){console.error('[BTC bootstrap]',e);window.BTC_BOOTSTRAP_ERROR=String(e&&e.message||e)});}
window.BTCBootstrap={version:function(){return window.BTC_APP_VERSION||null},loaded:loaded,applyVersion:applyVersion,boot:boot};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();